### ISSUE TITLE
RCA Variables and Concept IDs to submitParticipantData API

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connect#675] opened 2023-07-20 18:41 UTC
The below variables have been added to the data dictionary.  The sites will send as many data points as possible for a participant diagnosed with cancer through the submitParticipantData API.  Happy to provide more info as needed.  Thanks!

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/cunnaneaq/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/cunnaneaq/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Concept ID | Question Text | Variable Name
-- | -- | --
131461026 | How many   occurrences of cancer has the participant had? | RCAOper_NumCancOcc_v1r0
525972260 | Was the Connect   participant diagnosed with cancer? | RCAOper_CancerFlag_v1r0
345545422 | What date was   the participant identified as having cancer (the date of case ID)? | RCAOper_CancerDt_v1r0
939782495 | Anal | RCAOper_AnalCancer_v1r0
135725957 | Bladder | RCAOper_BladderCancer_v1r0
518416174 | Brain | RCAOper_BrainCancer_v1r0
847945207 | Breast | RCAOper_BreastCancer_v1r0
283025574 | Cervical | RCAOper_CervicalCancer_v1r0
942970912 | Colon/rectal | RCAOper_ColonCancer_v1r0
596122041 | Esophageal | RCAOper_EsophCancer_v1r0
489400183 | Head and neck   (Including cancers of the mouth, sinuses, nose, or throat. Not including   brain or skin cancers.) | RCAOper_HeadNeckCancer_v1r0
863246236 | Kidney | RCAOper_KidneyCancer_v1r0
607793249 | Leukemia (blood   and bone marrow) | RCAOper_Leukemia_v1r0
532172400 | Liver | RCAOper_LiverCancer_v1r0
754745617 | Lung or   bronchial | RCAOper_LungCancer_v1r0
665036297 | Non-Hodgkin's   lymphoma | RCAOper_NHLymphoma_v1r0
200837530 | Lymphoma | RCAOper_Lymphoma_v1r0
990319383 | Melanoma (skin) | RCAOper_Melanoma_v1r0
487917585 | Non-melanoma   skin (basal or squamous) | RCAOper_NonMelanoma_v1r0
603181162 | Ovarian | RCAOper_OvarianCancer_v1r0
482225200 | Pancreatic | RCAOper_PancreaCancer_v1r0
295976386 | Prostate | RCAOper_ProstateCancer_v1r0
764891959 | Stomach | RCAOper_StomachCancer_v1r0
248374037 | Testicular | RCAOper_TesticCancer_v1r0
139822395 | Thyroid | RCAOper_ThyroidCancer_v1r0
723614811 | Uterine   (endometrial) | RCAOper_UterineCancer_v1r0
807835037 | Other \|__\| | RCAOper_OtherCancer_v1r0
868006655 | Primary Cancer   Site- Another type of cancer: Please describe [text box] | RCAOper_OthCancerDesc_v1r0
178420302 | Unavailable/Unknown | RCAOper_UnknownCancer_v1r0
599128909 | What is the ICD   code for the primary cancer site diagnosed on 'date of case ID'? | RCAOper_CancSiteICD_v1r0
129461711 | Which version   of ICD coding did you use to report the primary cancer site? | RCAOper_ICDCodeVer_v1r0
457270069 | What is the   preliminary stage information for the cancer diagnosed on 'date of case ID'? | RCAOper_PrelimCancStg_v1r0
772638539 | How many tumors   were reported for the cancer diagnosed on 'date of case ID'? | RCAOper_TumorNum_v1r0

</body>

</html>

**Comment by cunnaneaq** [comment] 2023-11-01 14:06
This is the current version of the JSON - https://nih.app.box.com/file/1312388711307
@mnataraj92 is updating the data dictionary now

**Comment by JoeArmani** [comment] 2023-11-01 15:09
Hi @cunnaneaq, Thanks for the additional information. The doc answers most of my preliminary questions. Does the November scope include the need to trigger any surveys, or is it strictly receiving the data and putting it into the correct data structure?

**Comment by cunnaneaq** [comment] 2023-11-01 15:25
@JoeArmani focusing on receiving data in the correct structure for now.  Tentative timeline for the survey triggers is Feb-March '24.

**Comment by mnataraj92** [comment] 2023-11-01 16:50
dictionary is updated w/nesting in column AF

**Comment by JoeArmani** [comment] 2023-11-01 17:50
Perfect, thanks @cunnaneaq and @mnataraj92.

(1) I understand there can be many 'occurrences' per participant over time, my question is whether more than one 'occurrence' can happen each time the site submits data for a participant?

(2) Documenting that none of these are state variables in the data dictionary. These new variables are part of a new data structure in the participant profile. Please correct me if any of them are state variables.

(3) Will this data come in flat from the sites, or will it be nested? Examples below. Either is completely fine. It just impacts how I design the operation server-side.

```javascript
/*Site Submission Examples:*/

// Flat (all variables at the same level, we transform server-side):
data: {
    525972260: 353358909,
    637153953: [] /*site WOULD NOT submit the 'occurrence' cId, we would generate the structure server-side*/,
    345545422: Timestamp,
    599128909: ICD-O-3,
    740819233: [] /*site would not submit the 'primary site of cancer' cId, we would generate the structure server-side*/,
    135725957: 353358909 /*cancer types listed at same level as everything else*/,
    863246236: 104430631,
    // etc...
}

// Nested (site submits the data in the pre-designed nested structure):
data: {
    525972260: 353358909,
    637153953: [ /*site would submit the 'occurrence' cId with the pre-structured data*/
        {
            345545422: Timestamp,
            599128909: ICD-O-3,
            740819233: [ /*site would submit the 'primary site of cancer' cId with the pre-structured data*/
                135725957: 353358909 /*cancer types nested the way they will be in Firestore*/,
                863246236: 104430631,
                // etc...
            ],  
            // etc...
        },
    ],
}
```
(4) Regarding 'no' values: Do we want to include the 'no' value explicitly, or do we want that data point to be null?
Example: if a participant has a 'yes' value for melanoma and a 'no' value for lymphoma, do we want option A or B?
Option A probably provides more complete data for the analytics team. We do not need to require sites to submit 
'no' values in either case.

```javascript
/*Handling 'No' Values:*/

Option A:
990319383: 353358909,
200837530: 104430631,
// etc...all no values are explicitly listed in this option.

Option B:  
990319383: 353358909,
// all 'no' values are omitted (null) in this option.
```

**Comment by JoeArmani** [comment] 2023-11-02 17:02
Updates:
• 131461026 has been removed.
• If that count is needed, we can get that value from the number of 'occurrence' objects.

**Comment by JoeArmani** [comment] 2023-11-03 14:31
Thanks @cunnaneaq!

**Comment by mnataraj92** [comment] 2023-11-03 20:09
Hi @JoeArmani! for #4 regarding "no" values, I agree that explicit 'no' values are preferred. I was just wondering if any of these were going to be default variables? If so, I can indicate that in the dictionary.

**Comment by JoeArmani** [comment] 2023-11-07 14:46
Hi @mnataraj92, We already discussed this on Teams - thanks for answering my questions about default variables. Please disregard. I'm just adding here for documentation purposes.

This should be the complete list of cancer types. I'll be defaulting these 'no' when they're not included with an occurrence submission:
"939782495": 104430631,
"135725957": 104430631,
"518416174": 104430631,
"847945207": 104430631,
"283025574": 104430631,
"942970912": 104430631,
"596122041": 104430631,
"489400183": 104430631,
"863246236": 104430631,
"607793249": 104430631,
"532172400": 104430631,
"754745617": 104430631,
"665036297": 104430631,
"200837530": 104430631,
"990319383": 104430631,
"487917585": 104430631,
"603181162": 104430631,
"482225200": 104430631,
"295976386": 104430631,
"764891959": 104430631,
"248374037": 104430631,
"139822395": 104430631,
"723614811": 104430631,
"807835037": 104430631,
"178420302": 104430631

**Comment by JoeArmani** [comment] 2023-11-08 14:02
Update per @cunnaneaq: 599128909, 129461711, and 772638539 have been omitted from this API update as of this morning, 11/8.

**Comment by JoeArmani** [comment] 2023-11-14 16:17
Update: PR submitted for review https://github.com/episphere/connectFaas/pull/458

**Comment by cunnaneaq** [comment] 2023-11-15 14:13
Decision to allow API push to pass without stage information.  If stage information included only text with < 800 characters will pass.
Decision for API push to fail if primary cancer information is not provided.
@JoeArmani just documenting confirmation here

**Comment by cunnaneaq** [comment] 2023-11-15 14:31
@jacobmpeters @KELSEYDOWLING7
Tagging you here for info on the RCA to prepare for QC rules

**Comment by jacobmpeters** [comment] 2023-11-15 14:43
Thanks, Aileen.

**Comment by jacobmpeters** [comment] 2023-11-15 15:02
I updated the flattening of the participants table in dev. All of the new variables that have been tested here should now be available in the FlatConnect.participants_JP table in dev.

**Comment by Gbarra9** [comment] 2023-11-17 13:55
PR review status - Reviewing
- https://github.com/episphere/connectFaas/pull/458

**Comment by Gbarra9** [comment] 2023-11-17 19:24
PR review status - Approved, left comments

- https://github.com/episphere/connectFaas/pull/458

**Comment by JoeArmani** [comment] 2023-11-20 18:42
Here's the initial documentation for RCA Variables:
List of the variables with descriptions (excel): https://nih.app.box.com/file/1367482173536
Doc with passing and failing examples for developers at the sites: https://nih.app.box.com/file/1367487664518

**Comment by JoeArmani** [comment] 2023-11-24 17:31
This has been tested in dev. It's ready for stage.

**Comment by FrogGirl1123** [comment] 2023-11-30 16:10
As decided on the 11/29 punch list call, the nesting structure for the RCA data will be changed due to issues flattening arrays in the participants table.  As a result of needing to make these changes, RCA won't be released until Jan.

@JoeArmani please reach out to Nicole when you return from PTO to review the changes to the data structure.

**Comment by brotzmanmj** [comment] 2023-12-18 16:25
@JoeArmani Hi Joe, can you update with the latest status and the final decision for data structure? Thanks!

**Comment by JoeArmani** [comment] 2023-12-18 16:32
Hi @brotzmanmj, definitely. We're meeting at noon with the goal of finalizing this data structure, I hope to have that update posted by EOD, thanks.

**Comment by brotzmanmj** [comment] 2023-12-18 16:33
thanks!

**Comment by JoeArmani** [comment] 2023-12-18 19:09
@brotzmanmj 
Hi Michelle, I’m about to write up the final details. We have one final question for you below.

**Overview:**
•This data will come in from sites through the updateParticipantData API and will be stored in a new Firestore collection ‘cancerOccurrence’.
•The participant’s Connect ID and the sequential number of the occurrence will be stored with this data (i.e. occurrence 1, 2, 3, etc.) alongside the detailed occurrence data.

**Question:**
There is one item we’re requesting your decision on:

Concept ID 525972260 is a yes/no value with the question:
“Was the connect participant diagnosed with cancer?”

Originally, this was scheduled as a data point for the participant profile - to identify a positive ‘this patient has been diagnosed with cancer’ value.

The new data structure in cancer occurrences implies this value, but we’re not sure what future use-cases this might have.

So the question is how you’d like us to use this value:
Do you want us to include 525972260
-in the cancerOccurrence data?
-in the participant data?
-in both?
-in neither?

Thanks!

**Comment by brotzmanmj** [comment] 2023-12-18 19:24
Hi @JoeArmani, It's a good question. So perhaps this decision changed today but I think when we discussed last week, the Occurrences table was going to be built to be adaptable to include other illness and not just cancer, in which case the question might not be implied. Was it decided today that the table would just be CancerOccurrences? That might impact the answer to your question.

**Comment by JoeArmani** [comment] 2023-12-18 19:33
Hi @brotzmanmj, That makes sense. It was decided that this collection will specifically be cancerOccurrences. I believe this is due to the data team's BQ needs.

My understanding is the following:
Since the data points in the cancer occurrence object are specific to cancer occurrences, adding other types of occurrence data with different specifications would be detrimental to the complexity of the tables the data team needs to work with. Other occurrence data would widen and have unpopulated data types. I think it benefits the data team to have separate tables for each occurrence category in the future.

I'm going to request input from @jacobmpeters on this as well.

**Comment by brotzmanmj** [comment] 2023-12-18 19:41
That makes sense to me. In that case, the sites will only send data to CancerOccurrence table for participants with cancer occurrences known to the site, so it would make sense to me that it is implied and not necessary for them to send '525972260  “Was the connect participant diagnosed with cancer?" as part of the cancer occurrence table data. However, the list of variables requested for RCA were developed by Marie Josephe so I will defer to her. I'll email her and copy you. As far as the Participants table is concerned, I think it's not necessary to have this variable there either because in the next few months, we will change the SMDB to interact with the CancerOccurrences table.

**Comment by jacobmpeters** [comment] 2023-12-18 19:41
@brotzmanmj @jacobmpeters 

@FrogGirl1123 Communicated this suggestion to have the collection be a generic "occurrences" collection, so that future types of occurrences other than cancer diagnoses could be included in this collection. I mentioned that if new variables would be added for each type of occurrence, this would lead to an increasingly wide table with empty cells. 

After some discussion, we landed on the decision to just have a "cancerOccurances" collection for this use case.

**Comment by JoeArmani** [comment] 2023-12-18 19:46
Perfect, thanks @brotzmanmj @jacobmpeters @FrogGirl1123.

Marie Josephe, I'm not sure how to @ you here. I'll be documenting this today and early tomorrow. Please let me know if there are any changes/clarifications/etc. needed, and I'm available on Teams. Thanks.

**Comment by FrogGirl1123** [comment] 2023-12-19 19:54
From Marie Josephe in email yesterday "Mia envisioned this as a way to confirm that the transmitted data is indeed on a cancer diagnosis, and not on a preliminary report of suspected cancer. It is duplicative, and will not be informative on our end; it is a memory aid for the sites.  "

So 525972260 will remain as a question and in it's current location in the cancerOccurrence table documented here https://nih.app.box.com/file/1393159438842?s=3pemvj2oqylx4c1eez3n8oszqfmilf73.

**Comment by JoeArmani** [comment] 2023-12-19 20:05
Perfect. Thanks @FrogGirl1123.

**Comment by JoeArmani** [comment] 2023-12-19 20:18
### Update: Development is moving forward as of 12/19/23.

Here's the link to the updated details and data structure:
https://nih.app.box.com/file/1393159438842?s=3pemvj2oqylx4c1eez3n8oszqfmilf73.
It details the POST request from sites and the resulting 'cancerOccurrence' data.
I'll provide detailed documentation for sites upon completion.

Thanks to everyone for working together to get the updated requirements confirmed.

**Comment by JoeArmani** [comment] 2023-12-28 20:35
PR ready for review: https://github.com/episphere/connectFaas/pull/496

**Comment by jhflorey** [comment] 2024-01-10 15:47
Approved PR https://github.com/episphere/connectFaas/pull/496

**Comment by anthonypetersen** [comment] 2024-01-10 16:50
Reviewed & Approved

**Comment by JoeArmani** [comment] 2024-01-11 20:09
This is in dev and ready for testing. @cunnaneaq will be reaching out to sites for testing shortly.

**Comment by cunnaneaq** [comment] 2024-01-18 22:31
Update on decisions made 1/18/24 via email (@FrogGirl1123  @brotzmanmj @mnataraj92 @JoeArmani)

- Delete ICD (599128909), ICD Vers (129461711), and N tumors (772638539) from the data dictionary - @mnataraj92.  These don't need to be deprecated because they were never used in production.
- Limit primary cancer site (740819233) to 1 primary cancer per occurrence.  This decision was made to avoid confusion about which primary cancer is associated with the stage data sent.
- Keep the secondary source nesting structure to allow for a categorical response plus a text response if 'other cancer' is selected and add a CID for the question
- Require (868006655) 'primary cancer site - another type of cancer: Please describe [text box]' if (807835037) Other is selected
- Disallow (868006655) 'primary cancer site - another type of cancer: Please describe [text box]' if (807835037) Other is not selected

@JoeArmani will add the technical specs when ready

**Comment by JoeArmani** [comment] 2024-01-19 19:25
New requirements PR ready for review here: https://github.com/episphere/connectFaas/pull/509
I'll update the documentation shortly.

**Comment by brotzmanmj** [comment] 2024-01-24 13:44
@JoeArmani @mnataraj92 @cunnaneaq  Decision made 1/24/24 by Mia and Nico: Eliminate preliminary cancer stage (CID 457270069, RCAOcc_PrelimCancStg_v1r0) from RCA for the current release. (Further detail: We will add related variables to the RCA (including stage and death) in the next few release cycles after we are able to better understand the development of “suspense file” and how to capture the evolution of stage and likely other characteristics of the cancer).

**Comment by JoeArmani** [comment] 2024-01-24 16:37
PR for review: https://github.com/episphere/connectFaas/pull/518

**Comment by JoeArmani** [comment] 2024-01-24 20:19
This is in dev and ready for testing.

**Updated documentation:**
General technical info: https://nih.app.box.com/file/1393159438842
Examples for Sites: https://nih.app.box.com/file/1404701245622

**Comment by brotzmanmj** [comment] 2024-01-25 17:25
@cunnaneaq is moving forward with dev testing with Vijay. 

For future reference, in addition to considerations of vital status and cancer stage mentioned above, we will need a decision on whether we need a variable for manual review to confirm that the participant has been informed of their diagnosis. This will be for a later prod release, not the current one.

**Comment by cunnaneaq** [comment] 2024-01-25 18:30
Tracking the additional RCA variables under consideration for a future release here: https://github.com/episphere/connect/issues/866

**Comment by sonyekere** [comment] 2024-01-26 15:05
Vijay (HP) is still conducting testing updates in Dev. Prioritizing HP confirmation before moving forward with release timelines

**Comment by JoeArmani** [comment] 2024-01-29 15:01
Tested in dev, ready for stage.

**Comment by JoeArmani** [comment] 2024-01-31 21:40
Tested in stage, confirmed in Firestore and BQ. Ready for prod.

**Comment by JoeArmani** [comment] 2024-02-01 13:43
Closing, this is in production.

**Closed by JoeArmani** 2024-02-01 13:43 UTC
Labels: API
