### ISSUE TITLE
Fix bug in dry run of notifications

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#1107] opened 2024-08-30 17:21 UTC
Bug discovered in dry run of notifications ignoring message timing. Was found in PROMIS notification spec dry run. 
@we-ai has the details

**Comment by we-ai** [comment] 2024-08-30 20:40
The fix ([PR#640](https://github.com/episphere/connectFaas/pull/640)) is in dev. 
Since the bug is not impacting running code in production, the fix was not required to push to prod ASAP. It'll be in September release.

**Comment by we-ai** [comment] 2024-09-09 16:03
> Bug discovered in dry run of notifications ignoring message timing. Was found in PROMIS notification spec dry run. @we-ai has the details

The problem is that the dry run handler doesn't apply time settings (days, hours, minutes) to primary field, so the result is like setting time to zero (0). Since most of notification specs have all 0s in time settings with only a few spec exceptions (eg "3mo QOL Survey Reminders"), this bug wasn't identified earlier.

The fix is easy. It was tested locally on prod data and merged into dev branch.

**Comment by we-ai** [comment] 2024-09-09 17:51
When testing dry run functionality in dev, there were test data containing missing values (Connect_ID, etc) that blocked queries. To move dry run tests forward, 3 documents in dev Firestore were deleted, with token values as "fa106f55-95cd-4937-b3ea-def84bc0a4ba", "7b5f14f2-bb25-4ee0-908f-45cd1b362b47", "bdeb92fc-cd7d-4368-bbc1-0b6c6d895301".

**Comment by we-ai** [comment] 2024-09-09 18:37
When checking test data in dev, mixed data types were found in `participants` collection in Firestore. Doc with token "d98d59c9-ad91-46a3-bb51-e4c45dd2dae0" has a Connect_ID as "2526342253" which is a string and caused mixed data errors.
Connect_ID "2526342253" (string type) was updated to 2526342253 (integer type).

**Comment by HanaShiho** [comment] 2024-09-25 19:24
ready for stage

**Comment by HanaShiho** [comment] 2024-10-01 18:24
ready for prod

**Closed** 2024-10-03 11:52 UTC
Labels: CCC Priority 1
