### ISSUE TITLE
Handling of data updates

### ISSUE THREAD

**Issue by hannahem** [episphere/connect#53] opened 2020-02-14 15:43 UTC
Action Item from 2/5/2020 Feedback and Review Meeting: 

DCEG to determine how to handle data updates, possibly an error report system. We do not want to write over information, and want to document that a change is needed or a change happened.

**Comment by bhaumik55231** [comment] 2020-09-25 18:42
Duplicate of #149

**Closed by bhaumik55231** 2020-09-25 18:42 UTC
Labels: Connect API
