### ISSUE TITLE
Sendgrid Data Merge to Notifications Collection Table

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#828] opened 2023-11-27 17:21 UTC
sendgrid data is currently putting data in **sendgridTracking** w/in Firestore. Data to be merged/updated to **notifications table** in Firestore . 

Related: https://github.com/episphere/connect/issues/766

**Comment by sonyekere** [comment] 2023-12-04 15:33
Update in scope, issue not needed.

**Comment by brotzmanmj** [comment] 2023-12-05 14:44
Question to @jhflorey  about data merge to notifications collection table for December...  in requesting this I am making an assumption that the SendGrid data align 100% with messages in our Notifications table (the Notification table has the messages that were intended to be sent out, with message IDs associated with each). However, there may be at least one exception to this. Magic Link emails - if those are being sent from SendGrid, they will not have a corresponding record in the Notification table. Before Jessica works on the merge, @KELSEYDOWLING7 we should do a merge in BQ1 with the data we have in prod as of today and see how it aligns.

**Comment by jhflorey** [comment] 2023-12-05 15:12
@brotzmanmj  The logic of what I have implemented is that when Sendgrid returns the data includes `notification_id`. We will find a notification record with an id matching `notification_id`, if it exists we will update the notification record, otherwise it will be ignored (no more records are created in the collection Notification)

**Comment by brotzmanmj** [comment] 2023-12-05 15:17
@jhflorey that makes sense to me as long as we understand what messaged are getting ignored. The merge and analysis from Kelsey should help.

**Comment by jacobmpeters** [comment] 2023-12-05 17:20
@KELSEYDOWLING7 The FlatConnect.sendgridTracking_JP table is now available in Dev and Stg. 
There are currently no data in the PROD sendgridTracking table to be flattened.

**Comment by KELSEYDOWLING7** [comment] 2023-12-05 17:23
@jacobmpeters  Thanks Jake! 

@brotzmanmj  (This is based on stage and the presumption that prod tables would look identical once there's data)

Looking at Issue #766  -
 We do have both an email and token in both the Notifications Table and the SendGrid table so they would be able to be merged; note the Notifications Table does not have a Connect ID.
There doesn't seem to be any variable that lets us know whether or not the email was delivered in the Notifications Table like the "delivered_status" variable in the SendGrid table.
We have a "read" variable in the notifications table that I believe matches up with the "open_status" variable in the SendGrid table. Though I'm not sure if that lines up with the original request to see if they clicked links provided in the email



I was able to merge the two tables in BQ successfully:

SELECT *

FROM `nih-nci-dceg-connect-stg-5519.FlatConnect.sendgridTracking_JP` as SendGrid

INNER JOIN `nih-nci-dceg-connect-stg-5519.FlatConnect.notifications_JP`as notifications

ON SendGrid.email = notifications.email

**Comment by brotzmanmj** [comment] 2023-12-05 20:34
@jhflorey  there should be SendGrid data in prod as of today right? Can you let us know?

**Comment by brotzmanmj** [comment] 2023-12-05 20:38
@KELSEYDOWLING7  in the SendGrid table, there should be 9 variables from SendGrid (as in the screenshot in issue 766): delivered status, date, time, ; open status, date, time; processed status, date, time.

**Comment by brotzmanmj** [comment] 2023-12-05 20:40
@jhflorey and @KELSEYDOWLING7 can you work together on this to sort it out? thank you

**Comment by KELSEYDOWLING7** [comment] 2023-12-05 20:48
@brotzmanmj  There are currently 15 variables in the stage version of the flattened SendGrid table including delivered_status, delivered_date, delivered_timestamp, open_status, open_date, open_timestamp, processed_status, processed_date, processed_timestamp

![image](https://github.com/episphere/connect/assets/101136647/285821b2-0668-49a7-ad34-a44a900cedcc)


@jacobmpeters @jhflorey  Can you let me know once there is data in prod and the table has been flattened in prod?

**Comment by jacobmpeters** [comment] 2023-12-05 21:38
@jhflorey @KELSEYDOWLING7 

Right now, only the following variables are available in Connect.sendgridTracking in PROD:

fullname | mode | type | description
-- | -- | -- | --
__key__ | NULLABLE | RECORD |  
__error__ | REPEATED | STRING |  
__has_error__ | NULLABLE | BOOLEAN |  
__key__.namespace | NULLABLE | STRING |  
__key__.app | NULLABLE | STRING |  
__key__.path | NULLABLE | STRING |  
__key__.kind | NULLABLE | STRING |  
__key__.name | NULLABLE | STRING |  
__key__.id | NULLABLE | INTEGER

I can check again tomorrow, in case it is a timing thing..

**Comment by jhflorey** [comment] 2023-12-06 17:33
@brotzmanmj @jacobmpeters @KELSEYDOWLING7 Sorry for lately reply. Please check the image below for all events that we are able to receive from SendGrid
![image](https://github.com/episphere/connect/assets/24559107/f892e345-6a5e-403f-baa6-dfd2486211b5)

There are currently no data in the PROD sendgridTracking table to be flattened since we did not create `sendgridTracking` collection in firestore and did not enable `sendgrid event webhooks` for prod. 

I have already asked Tony to create `sendgridTracking`, i also enabled `sendgrid event webhooks` for prod.  We can check it tomorrow. Sorry for the inconvenience.

**Comment by jacobmpeters** [comment] 2023-12-07 18:09
Thank you, @jhflorey. 

@KELSEYDOWLING7 The sendgridTracking table is now in the FlatConnect dataset in BQ1-prod.

**Comment by KELSEYDOWLING7** [comment] 2023-12-07 18:26
Great thanks @jacobmpeters 

@jhflorey @brotzmanmj I was able to merge the two tables in prod successfully (the same way as in stage) and can confirm the variables identified above that were correctly in stage as expected are correctly in prod as expected

**Comment by brotzmanmj** [comment] 2023-12-08 20:58
Hi @rebexxxxxx and @KELSEYDOWLING7  I think we need to go about this a different way. We should be able to match on message ID and token. I would try it first in the direction of look at Notification table message ID and token and find the matched for those in the SendGrid table. Then see what is left in the SendGrid table that is not matched. All of them (or at least the vast majority of them) should be Magic Link emails.

**Comment by jhflorey** [comment] 2023-12-09 03:47
Hi @brotzmanmj @rebexxxxxx @KELSEYDOWLING7 we have a 'notification_id` field in the `sendgridTracking` collection that matches the `id`field in the `notifications` collection.

**Comment by KELSEYDOWLING7** [comment] 2023-12-11 13:40
@jhflorey  Great thanks! Which variable would tell us if the email was a magic link email?

**Comment by jhflorey** [comment] 2023-12-11 14:00
Hi @KELSEYDOWLING7 , as my understanding there are no record in `notificaitons` collection belongs to magic link email. it means the record in `sendgridTracking` collections that not have `notificaiton_id` field is from magic link email.

**Comment by sonyekere** [comment] 2023-12-11 16:10
Hello All, @jhflorey has pushed this to Dev. @KELSEYDOWLING7 @jacobmpeters

**Comment by rebexxxxxx** [comment] 2023-12-11 17:59
Hi @brotzmanmj, me and @KELSEYDOWLING7 worked on this again this morning, incorporating your helpful info about the message ID/ID variables from each table. As of this morning, the SG table has 1605 observations which are uniquely identified by the "notification_id" variable. The notification table has around 184k observations, uniquely identified by the "id" variable. I was able to merge these tables using notification_id/id and token, resulting in a perfect 1:1 merge. This means that all 1605 unique observations from sendgrid were matched to 1605 unique observations in the notifications table. So, to answer your original question, all observations from the sendgrid table are matched to an observation in the notifications table, and 1605 observations are matched from the notifications table to the sendgrid table.

**Comment by anthonypetersen** [comment] 2023-12-18 19:56
Will be removing this from December Release

**Comment by jhflorey** [comment] 2024-03-07 15:22
@brotzmanmj  @depietrodeanna @HanaShiho @we-ai 

-  Do we need to merge all the existing old data in the sendgridTracking collection into the notifications collection or do we only do this merge for the new data starting from this release?
- The list below is the data returned from Sendgrid. Which fields do you want to save to the notification collection? Pay attention to `events`, `timestamps`, `reasons`. 
- Which the events do we want to tracking (processed, deferred, delivered, open, click, bounce, dropped, spamreport, unsubscribe, group_unsubscribe, group_resubscribe)

```
[
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "processed",
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id"
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "deferred",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id",
    "response": "400 try again later",
    "attempt": "5"
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "delivered",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id",
    "response": "250 OK"
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "open",
    "sg_machine_open": false,
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255"
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "click",
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/"
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "bounce_classification": "invalid",
    "event": "bounce",
    "ip": "168.1.1.1",
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id",
    "reason": "500 unknown recipient",
    "status": "5.0.0"
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "dropped",
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id",
    "reason": "Bounced Address",
    "status": "5.0.0"
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "spamreport",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id"
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id"
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "group_unsubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "255.255.255.255",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  },
  {
    "email": "example@test.com",
    "timestamp": 1513299569,
    "smtp-id": "<14c5d75ce93.dfd.64b469@ismtpd-555>",
    "event": "group_resubscribe",
    "category": "cat facts",
    "sg_event_id": "sg_event_id",
    "sg_message_id": "sg_message_id",
    "useragent": "Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
    "ip": "000.000.000.000",
    "url": "http://www.sendgrid.com/",
    "asm_group_id": 10
  }
]
```

**Comment by depietrodeanna** [comment] 2024-03-07 18:13
@jhflorey  For your first question, I defer to Michelle and Warren.

For the second point, I would say "events," "timestamp," "reason," and "category," but perhaps others have thoughts. 

For the last point, I think all of these are useful save for "open" (since we will be using unique clicks as a proxy and we know there are issues with open rates). I am less sure about global and group unsubscribe at this time, since we don't have any specific categories of emails that people can unsubscribe from yet; all of the unsubscribes are "global" at this point. In the future, when we have options, it will be useful to include both group and global unsubscribes in the notifications table.

**Comment by brotzmanmj** [comment] 2024-03-08 15:22
@jhflorey and @we-ai I would think it would make the most sense to merge all the existing old data in the sendgridTracking collection into the notifications collection so all data will be in one place. I imagine that would be easier for the analytics team. @KELSEYDOWLING7  and @jacobmpeters thoughts on this?

For the data returned from SendGrid, what are we already capturing in SendGrid Tracking collection? I feel like we decided this back when we set that up so I don't want to go back on any decision that were made then. 
Another question: @jhflorey  Does the 'event' get overwritten or is each 'event' a unique yes/no type variable?

**Comment by KELSEYDOWLING7** [comment] 2024-03-08 15:26
@brotzmanmj I agree, I think it will be easier to have all the data in one place as opposed to split between two tables

**Comment by jacobmpeters** [comment] 2024-03-08 15:40
I agree. It would be great to have all of the data in the same place if this is feasible.

**Comment by jhflorey** [comment] 2024-03-08 15:53
@brotzmanmj `Another question: @jhflorey Does the 'event' get overwritten or is each 'event' a unique yes/no type variable?` => Currently each event will have 2 states, either `yes` or will not exist.

**Comment by jhflorey** [comment] 2024-03-08 15:57
@we-ai for merging all the existing old data in the sendgridTracking collection into the notifications collection. I suggest we create an api to do it. We will then remove it in the next release. Do you have any idea?

**Comment by FrogGirl1123** [comment] 2024-03-08 21:29
I support having all the data in one table. However it's important that any analyses take into account that many of the SendGrid variables, like click through, were not working correctly until the Magic Link was fixed.

**Comment by sonyekere** [comment] 2024-03-19 12:59
Hi, @rebexxxxxx and @jacobmpeters - this looks like this is in Dev now.

**Comment by jacobmpeters** [comment] 2024-03-19 20:58
@sonyekere @jhflorey @we-ai Is there anything in particular that you would like me to double check in DEV in BigQuery related to this issue? I looked at this table in BQ today and did not see any glaring issues, but I am not sure how to evaluate it.  Thanks for your thoughts..

**Comment by brotzmanmj** [comment] 2024-03-20 15:29
Hi @jhflorey can you let Jake know what he needs to look for so he can check it today? For example, which variables should exist now in the notifications table that did not before, and how to check if the SendGrid data is updating the correct 'row' in the notifications collection?

**Comment by jhflorey** [comment] 2024-03-20 16:01
Hi @jacobmpeters @brotzmanmj , We can check all the notifications that were sent yesterday by the job scheduler at (3pm and 8pm). If success they will have some fields `deliveredStatus`  `deliveredDate` `processedStatus` `processedDate`

**Comment by jacobmpeters** [comment] 2024-03-20 16:04
@jhflorey Thanks for the clarification. I will check this and report back.

**Comment by brotzmanmj** [comment] 2024-03-20 16:17
@jhflorey do we have one to check that failed?

**Comment by jhflorey** [comment] 2024-03-20 16:42
@brotzmanmj  we do not have now. we can try to send email to the invalid email.

**Comment by jacobmpeters** [comment] 2024-03-20 17:46
I see 49 notifications in the `Connect.notifications` table that were delivered yesterday. Each has a `deliveredStatus` of `true` and `processStatus` of `true`. However, all 54 have a `delveredDate` of 
approx. 2024-03-19T19:00:00.000Z 

```sql
SELECT
  notificationSpecificationsID,
  deliveredStatus,
  deliveredDate,
  processedStatus,
  processedDate
FROM
  `nih-nci-dceg-connect-dev.Connect.notifications`
WHERE deliveredDate BETWEEN "2024-03-19T19:00:00.000Z" AND "2024-03-19T19:10:00.000Z" -- 3/19/24 3:00-3:10 PM EST
   OR deliveredDate BETWEEN "2024-03-20T00:00:11.000Z" AND "2024-03-20T00:01:00.000Z" -- 3/19/24 8:00-8:10 PM EST
ORDER BY
  deliveredDate
```


notificationSpecificationsID | Row | deliveredStatus | deliveredDate | processedStatus | processedDate |
-- | -- | -- | -- | -- | -- | 
1 | 53380e52-a947-465c-b659-119df203bc7e | true | 2024-03-19T19:00:13.000Z | true | 2024-03-19T19:00:12.000Z |  
2 | 53380e52-a947-465c-b659-119df203bc7e | true | 2024-03-19T19:00:13.000Z | true | 2024-03-19T19:00:12.000Z |  
3 | 53380e52-a947-465c-b659-119df203bc7e | true | 2024-03-19T19:00:13.000Z | true | 2024-03-19T19:00:13.000Z |
... | ... | ... | ... | ... | .. |
49 | 6ab9e466-b31a-4d80-bf87-9401937badb0 | true | 2024-03-20T00:00:13.000Z | true | 2024-03-20T00:00:11.000Z |

Let me know if this is what you were expecting.

**Comment by jhflorey** [comment] 2024-03-21 13:37
@jacobmpeters  ` However, all 54 have a delveredDate of 3PM or 8PM on 3/19.` => i was wondering 49 or 54

**Comment by jhflorey** [comment] 2024-03-22 14:15
@jacobmpeters could you please check data of notifications today

**Comment by jhflorey** [comment] 2024-03-25 14:11
@jacobmpeters i think it's ready for stage. Please help confirm it.

**Comment by jacobmpeters** [comment] 2024-03-25 14:22
@jhflorey I'm working to confirm that my query is correct. Can you confirm what time zone the delivered date is given in?

**Comment by jhflorey** [comment] 2024-03-25 14:40
@jacobmpeters  there are 11 items of March 24
![image](https://github.com/episphere/connect/assets/24559107/e3b983fa-da69-43d5-971a-a0316a546498)

**Comment by jacobmpeters** [comment] 2024-03-25 15:20
What variables are those pairs of time stamps and ids associated with?

I see 26 records in the notifications table for March 24. 

<img width="348" alt="Screenshot 2024-03-25 at 11 20 13 AM" src="https://github.com/episphere/connect/assets/7967451/5b382a2f-9fe9-4ac3-9155-cff94196cc4a">

**Comment by jhflorey** [comment] 2024-03-25 16:13
@jacobmpeters It looks good for me if all 26 messages still have the deliveredDate. But i was wondering why in firestore have 11 items .

**Comment by jacobmpeters** [comment] 2024-03-25 16:30
I don't know why either. What query did you run to generate that list of 11 items? 

I've been sharing the code for my queries in hopes that we will figure out what is leading to the discrepancy.

**Comment by jhflorey** [comment] 2024-03-25 16:36
@jacobmpeters in firestore we do not have query. We use the method like this image below
![image](https://github.com/episphere/connect/assets/24559107/3871a56f-371f-4cbd-8d04-55f7b27993ce)

**Comment by jacobmpeters** [comment] 2024-03-25 16:55
I was just hoping you'd give me a reproducible example so I could confirm..

I ran the same query in BQ and Firestore and got 26 results in BQ and 11 in Firestore. I cannot account for the discrepancy.

<img width="348" alt="Screenshot 2024-03-25 at 12 50 21 PM" src="https://github.com/episphere/connect/assets/7967451/3577e679-e20e-46d4-86e0-9808e607726d">

<img width="597" alt="Screenshot 2024-03-25 at 12 51 10 PM" src="https://github.com/episphere/connect/assets/7967451/16ba1b1b-8faa-488e-8727-59616156d20c">

**Comment by jhflorey** [comment] 2024-03-25 17:00
@we-ai Do you have any ideas for this situation?

**Comment by sonyekere** [comment] 2024-03-25 17:27
@we-ai Alerting this is not ready for stage, could you assist to confirm the merge. Please reference the above discrepancy in Firestone that Jessica is experiencing when merging the data.

**Comment by we-ai** [comment] 2024-03-25 20:16
Counts based on my checks now (around 3:40pm, 3-25):
- 9 docs in `notifications` collection in Firestore
- 26 rows in `notifications` table in BQ

There're 2 things to consider when we see discrepancy like this:
- Data destructions delete notification docs in Firestore: all notifications related to a participant are deleted in `notifications` collection in Firestore, after a data destruction
- Data in `notifications` collection in Firestore are synced once to BQ at 11PM daily.

So the count discrepancy between Firestore and BigQuery isn't an issue, if we know notification records are deleted as expected during data destructions.

**Comment by jacobmpeters** [comment] 2024-03-25 20:35
Thanks for clarifying, @we-ai.  Glad to hear that you are not concerned. 

I was not aware of this, but I now see in the Cloud Scheduler that `Daily-Notifications-Backup` [daily, @ 11 PM] is decoupled from the `Backup-Firestore` [every 2 hrs]. 

It makes sense now that if the timing was decoupled and notifications were being deleted for an unrelated test (i.e, data destruction) I could not verify anything based on time stamps alone.

**Comment by sonyekere** [comment] 2024-03-25 22:13
@brotzmanmj Please see Warren and Jake's feedback regarding the discrepancies Jessica found in Firestore vs BigQuery. Please confirm if to further discuss or proceed with dev to stage sync

**Comment by brotzmanmj** [comment] 2024-03-25 22:22
@sonyekere  I believe @FrogGirl1123 wanted the data types to be fixed to be consistent before this moves to prod (for variables that are not already in prod). I defer to her. Thanks.

**Comment by we-ai** [comment] 2024-03-26 07:16
@brotzmanmj The mixed data types discussed earlier today are old issues not related to sendgrid data merges. If things (data merges and formats, notification deletions after data destruction) look fine here, the updated code related to this issue should be ready for stage.

**Comment by we-ai** [comment] 2024-03-26 07:45
Related to data merges, the data in `notifications` in Firestore are not consistent. 2 versions of some keys ("bounceStatus" and "bounce_status", "processedStatus" and"processed_status", etc. ) are used across documents. Please make corrections and use only camelCase for keys. @jhflorey

**Comment by sonyekere** [comment] 2024-03-26 13:27
@we-ai and @jhflorey @jacobmpeters The team has decided this is ready for stage. Please be mindful that data destruction/notifications may impact different counts in firestorm and BigQuery. @jhflorey Please keep an eye out

**Comment by jhflorey** [comment] 2024-03-26 13:34
> Related to data merges, the data in `notifications` in Firestore are not consistent. 2 versions of some keys ("bounceStatus" and "bounce_status", "processedStatus" and"processed_status", etc. ) are used across documents. Please make corrections and use only camelCase for keys. @jhflorey

No worry, some snakeCase in dev are from my testing before. I've already updated to cameCase.

**Comment by we-ai** [comment] 2024-03-26 14:43
> No worry, some snakeCase in dev are from my testing before. I've already updated to cameCase.

I have a different view: the data should be kept tidy when possible. 
The `notifications` collection in prod doesn't have mixed keys, but dev and stage `notifications` collections do. I suggest to correct existing snake_case keys instead of ignoring them.

**Comment by jhflorey** [comment] 2024-03-26 15:00
@warren i'll write a script to fix it.

**Comment by jhflorey** [comment] 2024-03-27 13:29
@jacobmpeters Please help check it in BQ
<img width="1033" alt="image" src="https://github.com/episphere/connect/assets/24559107/514a1f67-1811-4823-affa-e2de34e56e98">

**Comment by jacobmpeters** [comment] 2024-03-27 13:38
@jhflorey Yes, I will work on this now and confirm when done. Thanks for providing these details.

**Comment by jacobmpeters** [comment] 2024-03-27 14:03
@jhflorey 

The BQ data look good to me.

```sql
SELECT
  __key__.name,
  deliveredDate,
  notification.title,
  notificationSpecificationsID,
  id,
  notificationType,
  category,
  attempt
FROM `nih-nci-dceg-connect-stg-5519.Connect.notifications`
WHERE deliveredDate > "2024-03-27T00:00:00.000Z"
ORDER BY deliveredDate DESC
```

| Row | <br>name<br> | <br>deliveredDate<br> | <br>title<br> | <br>notificationType<br> | <br>category<br> | <br>attempt<br> |
|---|---|---|---|---|---|---|
| 1 | IOy1J3ixp6TzUBy4A1K0 | 2024-03-27T00:00:14.000Z | We still need your mouthwash sample for Connect | email | Baseline Mouthwash Home Collection Kit Reminders | 3rd contact |
| 2 | 7wI3YuSDGtqvdF6Ig3NT | 2024-03-27T00:00:14.000Z | Please answer a short survey about your samples | email | Baseline Research Biospecimen Survey Reminders | 2nd contact |
| 3 | LLtHjbLEaUCSCX1GtgyD | 2024-03-27T00:00:13.000Z | Please answer a short survey about your samples | email | Baseline Clinical Blood and Urine Sample Survey Reminders | 2nd contact |
| 4 | pcxWbR5cZeVn518DQZ9f | 2024-03-27T00:00:12.000Z | Please answer a short survey about your samples | email | Baseline Clinical Blood and Urine Sample Survey Reminders | 2nd contact |
| 5 | EnDxnru9T7CNRZ9ttYPh | 2024-03-27T00:00:12.000Z | Please answer a short survey about your samples | email | Baseline Clinical Blood and Urine Sample Survey Reminders | 2nd contact |
| 6 | BEmRI4oTGOg03h1tltm5 | 2024-03-27T00:00:12.000Z | Please answer a short survey about your samples | email | Baseline Clinical Blood and Urine Sample Survey Reminders | 2nd contact |
| 7 | z6xr4TlzPCm7dds0Mld1 | 2024-03-27T00:00:12.000Z | Please answer a short survey about your samples | email | Baseline Clinical Blood and Urine Sample Survey Reminders | 2nd contact |

**Comment by jhflorey** [comment] 2024-03-27 14:11
@jacobmpeters greate. I think it's ready for prod.

**Comment by jhflorey** [comment] 2024-03-27 15:11
> > No worry, some snakeCase in dev are from my testing before. I've already updated to cameCase.
> 
> I have a different view: the data should be kept tidy when possible. The `notifications` collection in prod doesn't have mixed keys, but dev and stage `notifications` collections do. I suggest to correct existing snake_case keys instead of ignoring them.

@we-ai this is the script to convert to camelCase. Please help review it.

**Comment by we-ai** [comment] 2024-03-27 18:18
> @we-ai this is the script to convert to camelCase. Please help review it. https://app.box.com/s/proj9zf9scz1ik4drwkwvw94zm3kflrs

Please send your code for dev team review.

**Comment by sonyekere** [comment] 2024-03-29 13:52
Closing issue, item is in Prod.

**Closed** 2024-03-29 13:51 UTC
