### ISSUE TITLE
Refusal/Withdrawal derived variable not setting to Yes for some participants

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#864] opened 2024-01-24 15:05 UTC
KPCO reported a recent withdrawal that did not come through the API call for refusal/withdrawals. We found that the 'any refusal or withdrawal' derived variable CID 451953807 was not set = Yes for this individual.

We ran a file of all refusals and withdrawals and found that 115 of 360 individuals on the list do not have the derived variable set to yes, including some recent ones and some past ones. So far no apparent reason.... it doesn't seem to be any one type of refusal or withdrawal that was left out of the derivation, for example.

See list on Box: https://nih.app.box.com/file/1423854670887

Including @mnataraj92 to this issue, please work with Kelsey and Jake to add a QC check for this going forward

**Comment by jacobmpeters** [comment] 2024-01-24 19:29
@brotzmanmj Thank you for the information. @mnataraj92 and I discussed this briefly today and plan to meet early next week to discuss how to incorporate a QC check for this.

**Comment by JoeArmani** [comment] 2024-01-24 19:53
@brotzmanmj 
I found the likely source of this derived variable bug, and unfortunately, I think the inconsistencies (between December and January releases) were caused by my code from the December release. It probably extends to other places where checkDerivedVariables needed to update the participant profile with new derived variables from the updateParticipantData API.

### The immediately noticeable issue to address:
**Process:**
The checkDerivedVariables function reads participant data to update the participant’s derived variables. This is supposed to happen after the updated data is written to the participant profile.

**Bug:**
checkDerivedVariables was not properly waiting for the participant profile top update since the December release. This causes intermittent timing issues where checkDerivedVariables receives the participantData prior to the update being written. 

It looks like we’ve seen a spike in inconsistencies in this data since the December release. I believe this is the source. It likely impacts other derived variables as well. 

**What has been happening since the last release (updateParticipantData API):**
The participant profile receives the data update. checkDerivedVariables starts executing concurrently. It pulls the participant data, sometimes receiving participant data before the updated data is written. In those cases, checkDerivedVariables isn’t receiving the correct data to process derived variables (it’s receiving the old data), so those variables aren’t being updated.

This timing will be resolved in the upcoming prod push, but it has impacted some derived variable data between the December and January releases.

### Resolution:
With the write timing issue resolved, we could run the checkDerivedVariables function on participants to correct for issues where derived updates were missed. This should resolve inconsistencies.
•If we have a specific list of impacted participants (Connect_IDs or tokens), that would be ideal.
•This could also be run on all participants if needed.


### Other items likely causing prior inconsistencies:
•updateParticipantData and checkDerivedVariables run separately. This means checkDerivedVariables could fail even when updateParticpantData succeeds. This is also true for the submit (storeResponse) function in ConnectApp. This could lead to infrequent inconsistencies where the first operation succeeds and the second operation fails without setting off an error.

If there’s time, it would be beneficial to run this functionality together to ensure consistency in participant profile updates. We could handle this by:
(1) Running the checkDerivedVariables function on the updated participant data.
(2) Processing the participant profile update with one write operation that either passes or fails (with updated participant data and derived variables data combined).

This way, we can detect errors, and data will remain consistent instead of using sequential write operations. 


**Additional Notes on ‘other’ items:**
•There are small related items to handle in SMDB and Biospecimen related to updating participants and calling the checkDerivedVariables function if we update this approach to handling derived variables alongside participant profile updates.

•SMDB withdrawal-related code should wait for a response from updateParticipantData API.

**Comment by JoeArmani** [comment] 2024-01-25 14:46
Function -> Fix derived data ready for review: https://gist.github.com/JoeArmani/8f69efde551f249a613a688f268c2ea0

Putting together documentation for the data team now, I'll update this comment when it's ready.

**Comment by JoeArmani** [comment] 2024-01-25 18:54
@brotzmanmj 
Hotfix: https://github.com/episphere/connectFaas/pull/522 is live in prod. The timing issue with checkDerivedVariables is resolved moving forward.

I am currently testing/finalizing the retroactive fix for missed updates since the December prod push.

**Comment by JoeArmani** [comment] 2024-01-25 21:58
The 'fix' function completed team & lead reviews and ran successfully in dev. Ready to go.

**Comment by JoeArmani** [comment] 2024-01-25 23:42
@brotzmanmj 
The 'check derived variables' update ran as expected for all verified participants this evening. I manually verified the KPCO and KPHI participants from the recent Gitter issue - those are updated as expected, and the KP developer has been notified that results should now be available.

**Comment by brotzmanmj** [comment] 2024-01-25 23:46
Thank you @JoeArmani ! 

@kmazzilli  can you ask Kelsey to re-run the refusal/withdrawal list with the derived 'any refusal or withdrawal' variable included so we can confirm that it's 'yes' for the entire list?

**Comment by kmazzilli** [comment] 2024-01-26 16:54
[RefusalWithdrawl_cases_2024-01-26_boxfolder_141543243283.csv](https://github.com/episphere/connect/files/14067391/RefusalWithdrawl_cases_2024-01-26_boxfolder_141543243283.csv)

**Comment by brotzmanmj** [comment] 2024-01-26 17:19
Thanks Kaitlyn and Kelsey. @JoeArmani it looks like the derivation update was successful and backfilled the missing derived variable so that's a good confirmation. The two people still missing the derived variable for 'any refusal or withdrawal' have Verification Status = 'Not Yet Verified'. (This occurs rarely where someone consents and then withdraws without submitting their user profile so they don't go through the verification process). I hadn't considered these rare cases when we limited the backlog update to Verified participants. Suggestions on how to proceed?

**Comment by JoeArmani** [comment] 2024-01-26 17:36
@brotzmanmj
Thanks for confirmation on the first part. I can confirm we only ran this on 'verified' participants.

If only two participants need to be updated, we can either:
(1) Manually update those two participants, or
(2) Run the same function on all 'not yet verified' participants.

The manual update is quicker. Running the function on 'not yet verified' participants would catch any other missed updates that are processed by the 'check derived variables' function.

I think 'any refusal or withdrawal' is the only value that would be updated for 'not yet verified' participants, but here's the list of items checked by the function for your reference & decision:
- incentiveEligible
- menstrualCycleSurveyEligible
- allBaselineComplete
- bloodUrineNotRefused
- calculateBaselineOrderPlaced
- clinicalSampleDonated
- anyRefusalWithdrawal

**Comment by brotzmanmj** [comment] 2024-01-26 18:44
@JoeArmani  I agree the 'anyRefusalWithdrawal' is the only one that would be applicable in an operational sense to a 'not yet verified' person. I'm fine with a manual update.
@mnataraj92  can you add this to the prod manual change log for those two Connect IDs and I'll approve?

**Comment by brotzmanmj** [comment] 2024-01-29 14:12
And @JoeArmani one more question... The list of 7 items about that are part of the 'check derived variables'... that doesn't encompass all derived variables that exist for Connect. Are other derived variables just not part of the function? I'm wondering because we are going to work on shoring up the QC for all derived variables and it would help us to understand the distinction. Thanks.

**Comment by JoeArmani** [comment] 2024-01-29 14:38
@brotzmanmj Sure, these are the seven items handled in the `checkDerivedVariables` function. Based on what I see, these are more complex derivation cases. Other derived variables seem to be handled with a more direct approach -- alongside the updates that cause their derivations.

For instance, based on two items I've worked on:
• Derived variables for cancer occurrences are directly handled in the section of code that validates, prepares, and updates cancer occurrences.
• Derived variables for death data are directly handled in the update that validates and processes death data.

Please let me know if you need any additional info on this.

**Comment by brotzmanmj** [comment] 2024-01-29 14:42
Hi @JoeArmani  Thanks for the explanation. @mnataraj92  and @jacobmpeters  are going to be working on adding to the QC code to make sure it includes a check on all derived variables. From what you describe, for their purpose, I think the best source to identify all derived variables is the Data Dictionary, regardless of where they are derived in the code.

**Comment by JoeArmani** [comment] 2024-01-29 14:59
@mnataraj92 @jacobmpeters I put together an initial doc with derivations from the checkDerivedVariables function - I think Kelsey added that to Box. Let me know if you need me to check/confirm other derivations on the DevOps side.

**Comment by JoeArmani** [comment] 2024-01-29 15:24
@KELSEYDOWLING7 I'll look into these and send you an updated version of the doc from Friday

**Comment by mnataraj92** [comment] 2024-01-29 17:19
> @JoeArmani I agree the 'anyRefusalWithdrawal' is the only one that would be applicable in an operational sense to a 'not yet verified' person. I'm fine with a manual update. @mnataraj92 can you add this to the prod manual change log for those two Connect IDs and I'll approve?

Added to the prod change log!

**Comment by mnataraj92** [comment] 2024-02-02 16:30
This change has been made in prod

**Comment by KELSEYDOWLING7** [comment] 2024-03-05 14:48
@JoeArmani Hi Joe, yes this is complete on our side. All of the derived variables have updated or new QC rules

**Comment by JoeArmani** [comment] 2024-03-05 14:52
Great. Thanks @KELSEYDOWLING7. Closing.

**Closed by JoeArmani** 2024-03-05 14:52 UTC
Labels: Bug
