### ISSUE TITLE
Distinguish "newsletter" into two separate categories in SMDB based on message (April Release)

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#943] opened 2024-03-28 22:21 UTC
@we-ai and @KELSEYDOWLING7 does it work to use “quarterly newsletter” as the category name for eNewsletter emails, and change the category name for the one year study anniversary email to something different like “one year anniversary message?" I think that would be the best way to distinguish these different types of stylized emails moving forward. Is there any functionality you need to work on to make sure this works when programmed into SMDB @we-ai?

**Comment by we-ai** [comment] 2024-03-29 02:14
I need to adjust some condition checks to match these new category names.
Although arbitrarily any string works for computers, I prefer concise names for the 2 categories. How about `eNewsletter` for one-time newsletter specs and `anniversaryNewsletter` for the one-year newsletter spec? When using unreadable characters (like spaces), it's easy to make mistakes (like 2 or more spaces in text) and hard to find out.

**Comment by depietrodeanna** [comment] 2024-03-29 03:21
I'm fine with using category names as you described. You'll notice our other notification categories are long and have multiple spaces. Moving forward, we'll consider category naming in single string, concise phrases. Tagging @HanaShiho to note this and add to the notification development and testing SOP.

**Comment by we-ai** [comment] 2024-04-10 16:35
Hi @brotzmanmj, the one-year anniversary email is not goring out because the time was incorrectly set. Based the current time setting, the anniversary emails are sent out from 4-26-2024. Deanna tested and confirmed that, after fix the email time issue, the stage anniversary emails work normally.

Using 1 or 2 categories for newsletters doesn't affect emails sending. As we discussed earlier, using 2 categories make data management downstream easier.

**Comment by depietrodeanna** [comment] 2024-04-10 16:44
Hi @we-ai  Jessica is still fixing the format of the study anniversary newsletter issue, so this not going out in production until that is addressed. Once the format issue is addressed and the anniversary newsletter renders correctly, I will update the prod conditionality and we will be able to track this going out from that point forward. I will make the new anniversary newsletter category as you described above, and when we program the next eNewsletter I will use the appropriate category name for that as well. We'll be sure to test those new category names as well as we conduct lower tier testing.

**Comment by we-ai** [comment] 2024-04-10 22:44
These 2 newsletter categories (`eNewsletter` and `anniversaryNewsletter`) will be supported in prod after this release. 

If quarterly newsletter template in April is run before prod launch, please still put the spec in `newsletter` category, as before. And also test it in dev and stage using the same category.

**Comment by depietrodeanna** [comment] 2024-04-10 23:23
@we-ai we are testing the new quarterly newsletter in dev now- should be be using "eNewsletter" or "newsletter" as category for testing? In other words, are these two categories supported in dev for testing?

**Comment by we-ai** [comment] 2024-04-11 12:37
@depietrodeanna Yes, the new categories will be in dev for testing.

**Comment by HanaShiho** [comment] 2024-04-19 19:41
Tested in dev, ready for stage

**Closed** 2024-04-25 13:27 UTC
Labels: CCC Priority 1
