### ISSUE TITLE
Collections showing up in Shipping dashboard after they have been shipped and received (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#833] opened 2023-12-01 14:49 UTC
HF had an issue this week where 3 collections showed back up on the Shipping dashboard after they had been shipped and received by BPTL.  Below is what happened to cause the collections to show back up on the shipping page:

1 - Collections CXA006956, CXA006935, CXA006958, and CXA006980 were physically packaged in Box 530 FedEx tracking number 635213599543 and shipped to BPTL
2 - Only Collections CXA006956, CXA006935, and CXA006958 were electronically included in the package in the shipping dashboard.  CXA006980 was not included electronically and was not listed on the manifest.
3 - BPTL notified HF that CXA006980 was physically received but was not listed on the manifest and asked them to electronically ship the collection in the dashboard.
4 - HF realized collection CXA006980 was not listed on the shipping dashboard, went back to the data entry screen and reviewed the specimen info on each of these four samples, selected review complete, then review finalized.  They re-finalized all 4 of the collections and not just the collection that was missing.  
5 - all 4 collections now showed in the available collections list on the shipping dashboard.
 
Actions taken:
1 - Kathleen tested this scenario in the dev dashboard and was able to recreate the issue
2 - We asked HF to electronically ship CXA006980, but to hold off on doing anything with the other 3 collections.
 
What is needed:
1 - Discussion on how we can handle the 3 collections still listed on their dashboard that have already been received in BPTL's dashboard.  
2 - figure out why this is happening.  We had tested similar scenarios with orphan tubes being entered and shipped after the main portion of the collection had been shipped and received and did not come across this issue.  Is this just something we missed or has something changed on the backend?  Usually if we try to ship something that has already shipped we get an error message stating it had already shipped.

**Comment by sonyekere** [comment] 2023-12-05 18:36
Joe to review 12/5

**Comment by JoeArmani** [comment] 2023-12-05 20:31
Initial thoughts: This issue stems from re-finalizing the collections.

**Background:**
-When a collection is finalized, that collection gets a 'boxedStatus' property (cid 771580890) of 'notBoxed' (cid 657483796).

-As specimens in the collection get boxed, that property shifts to 'partiallyBoxed' and finally 'boxed'.

-The 'partiallyBoxed' property accounts for stray tube handling and separation of mouthwash tubes from the rest of the tubes (this is important for identifying strays and separating bags 0008 & 0009).

-The 'boxed' property means all tubes are accounted for and in boxes. Once a specimen's status is 'boxed', it is no longer included in the shipping dashboard's available collections search. This was a major factor that reduced our former high data in transit problem.

-'notBoxed' and 'partiallyBoxed' specimens are fetched in separate requests to optimize the fetch process.

-These properties are part of the optimized search function that allows us to only pull the data we need when a user loads or refreshes the dashboard.

**The important part:**
_Re-finalizing the collection currently takes the same action it does initially. It sets the collection's 'boxedStatus' to 'notBoxed.'_
 
This would make even a boxed/shipped/received collection show up in the shipping dashboard since we're currently only checking boxed status. I can confirm I did not plan for finalized collections to be 're-finalized' when building these data structures & algorithms, so this 're-finalized' scenario is not yet handled and the shipping dashboard's behavior in this scenario makes sense based on the current design.

Current collection status (prod) is in line with expectations based on current functionality:
CXA006956: 'notBoxed'
CXA006935: 'notBoxed'
CXA006958: 'notBoxed'
CXA006980: 'boxed'


**Questions:**
How common is it for a collection to be re-finalized?
Is this a situation expected -- should plan for and handle accordingly?

**Comment by StephanieWeinstein** [comment] 2023-12-05 20:44
Hi Joe,
Thanks for exploring that and explaining it so well!
It is not common for a collection to be re-finalized (has only happened this one time since you implemented your changes), but I do think we want to leave this capability in case a stray tube is found, for example.
Would you be able to update the code so that a collection cannot be re finalized if it is already shipped?
@brotzmanmj , would that solve our problem?

**Comment by JoeArmani** [comment] 2023-12-05 20:52
Hi @StephanieWeinstein,

Great, I'm glad that explanation was clear.

We can do that for sure. The cleanest way would be to check the boxed status property in the specimen when someone tries to finalize it. If it already exists, we skip updating that value.

Are there any reasons other than this scenario that a site needs to re-finalize a collection? I ask in case there are other situations I need to account for in the code. Thanks!

**Comment by JoeArmani** [comment] 2023-12-05 22:37
@brotzmanmj Hi Michelle, I just tested this functionality in dev. I finalized collection CXA464646. After finalizing:

-I can search, load, and finalize the collection again. Based on this issue above (#833), it sounds like that's what the site did last week.
-Also, previously unedited tubes can be updated and saved along with the re-finalization process.

I confirmed this data in Firestore and by searching the collection in Biospecimen again (a third time) after updating.

Based on your message, it sounds like this is not the desired outcome. Let me know what we're looking for here -- This part of the app is new to me (minus the null streck tube fix), but we can certainly get it working as intended.

**Comment by StephanieWeinstein** [comment] 2023-12-08 21:59
Hi @JoeArmani,
I just talked this through with Michelle.
 
Sites should not be able to / not need to re-finalize a collection if nothing has changed.
 
Sites should only be able to re-finalize a collection if something new was added (like they added a stray blood tube or a missing urine tube).  This new tube might still be shipped in the same box as everything else with the same collection ID, or might be shipped in a separate box.
 
Let us know if you need to talk it through!
Stephanie

**Comment by JoeArmani** [comment] 2023-12-11 14:11
@StephanieWeinstein Perfect. Thanks for defining these requirements. This makes sense and I'll reach out with any questions.

•allow re-finalizing on updates to a collection.
•disallow re-finalizing if no changes have occurred. Boxed status should not be updated if no tubes have been added.
•integrate boxedStatus property with re-finalization -- if tubes are added, boxed status needs to be 'not boxed' or 'partially boxed' depending on status of the existing tubes.

**Comment by JoeArmani** [comment] 2023-12-15 20:00
@StephanieWeinstein 
I've had a bit of time to dig into this and get a feel for the user's flow through this part of the app. Here are my thoughts. Please let me know if you have any feedback/suggestions/requested changes to this proposed behavior. Thanks.

**Unfinalized collections:**
Normal operation, no changes.

**Finalized collections:**
Both the "Save" and "Go to Review" buttons save any changes to the collection (this is existing behavior).
If user clicks either of these buttons, they're attempting to update an already-finalized collection. The app will prompt the user with a “Collection already finalized” warning modal. Click ‘cancel’ to exit or click ‘continue’ to continue the update.

Modal screenshot:
![Image](https://github.com/episphere/connect/assets/93854858/f659d985-3d41-437e-a2af-1d616bc17d6b)
On clicking "Cancel" the modal closes without saving changes. The editing form is still active with any current updates.

On clicking "Continue” from the warning modal:
(1) We check whether any new tubes have been added to the collection. We manage the boxed status and stray tube data alongside the save operation (these are needed for shipping dashboard functionality). We do not update the finalized status or original finalized timestamp since they’re already recorded.
*Please advise on this finalized timestamp - it was just my guess that we want to retain the original finalized timestamp.

(2) Since the collection has been finalized previously, it the finalized property and initial finalized timestamp are retained throughout the process to ensure continuous shipping dashboard compatibility.

(3) If a user tries to ‘re-finalize’ an already finalized collection, the correct data with any additional new tubes has already been saved with the "Continue" button click in the warning modal from the Collection Data Entry screen. No action is needed here since all the properties are already accurately set (we did this in the previous screen). The user can confirm re-finalization without issue, and our code ensures none of the shipping dashboard properties are overwritten.
—-

This is the best UX & data management method I've come up with. It records any changes to the collection, gives users the functionality they’re used to, handles the data appropriately, doesn't limit navigation or button clicks, doesn't require tracking any additional data points related to strays or re-finalizing, and works even if the rest of the collection has already been boxed & shipped.

**Comment by StephanieWeinstein** [comment] 2023-12-15 21:18
Hi @JoeArmani ,
I confess I don't understand some of this, but your solution seems good.  I'm a bit confused about the warning modal though.  We are ok with them clicking through if they meant to update the collection and re-finalize, right?  So maybe the wording could be "IMPORTANT: This collection has already been finalized. Click continue if you want to update the collection and re-finalize.  Click Cancel to discard changes."

I'm fine with retaining the original finalized time stamp.  
Thank you so much for all your work on this!
Stephanie

**Comment by JoeArmani** [comment] 2023-12-15 21:30
Thanks @StephanieWeinstein, I appreciate your feedback on this.

I'll get the modal text updated. We can also remove it entirely if you'd like.

I only added the modal to avoid accidental editing of a finalized collection. The only scenario I was considering for this case would be an accidental scan (or a typo in the collection ID search) on the wrong collection ID. Maybe this is a realistic scenario, maybe it isn't. Please let me know your preference on the modal, and we should be all set.

Thanks!

**Comment by StephanieWeinstein** [comment] 2023-12-18 14:28
Hi @JoeArmani ,
Let's keep the modal.
Thank you!
Stephanie

**Comment by JoeArmani** [comment] 2023-12-18 15:24
Perfect. Thanks, Stephanie. This will be in PR once our dev freeze is lifted.

**Comment by JoeArmani** [comment] 2024-01-02 16:49
PRs ready for review:
Biospecimen - https://github.com/episphere/biospecimen/pull/648
ConnectFaas - https://github.com/episphere/connectFaas/pull/497

**Comment by Gbarra9** [comment] 2024-01-10 14:01
PR Review Status - Approved

- https://github.com/episphere/biospecimen/pull/648 (Approved, left comments)
- https://github.com/episphere/connectFaas/pull/497 (Approved)

**Comment by jhflorey** [comment] 2024-01-10 16:11
Approved 2 PRs 

- https://github.com/episphere/biospecimen/pull/648
- https://github.com/episphere/connectFaas/pull/497

**Comment by anthonypetersen** [comment] 2024-01-10 17:51
Approved & Reviewed:
* https://github.com/episphere/connectFaas/pull/497

**Comment by JoeArmani** [comment] 2024-01-10 22:15
Merged to dev, ready for testing

**Comment by sonyekere** [comment] 2024-01-23 18:12
Create additional issue to clean up the listing post push. Kathleen to finalize listing.

**Comment by wyattks** [comment] 2024-01-29 18:45
SFH - 1 sample (CXA010562 0009) shipped on 1/26/2024 and received 1/27/2024 showed up on the packaging dashboard.

Here is a running list of all samples showing back up on the shipping dashboard after being shipped.
https://nih.app.box.com/file/1423877116400

**Comment by JoeArmani** [comment] 2024-01-29 18:50
Thanks, I'll look into this list shortly.

**Comment by JoeArmani** [comment] 2024-01-30 16:33
@wyattks For CXA010562, Box490 - I confirmed finalization happened just after ‘submit shipment’ on this one, so it’s the same ‘re-finalization’ issue. I double-checked, and all other collections on the list have been updated and recorded in the change log.
 I’ll reach out for permission to update CXA010562.

**Comment by wyattks** [comment] 2024-01-31 15:31
Thank you Joe

Erin tested scenarios like this in Stage and did not have the collections should back up on the shipping dashboard.
Ready for prod

**Comment by JoeArmani** [comment] 2024-02-01 13:45
Closing. This is in production.

**Closed by JoeArmani** 2024-02-01 13:45 UTC
Labels: Bug, Biospecimen Dashboard, Shipping Dashboard
