### ISSUE TITLE
SMDB Participation Status not updating with EMR deceased info

### ISSUE THREAD

**Issue by kmazzilli** [episphere/connect#856] opened 2024-01-08 18:02 UTC
For context - We have two ways to find out about deaths of Connect participants. The first is someone who knows the participant (a spouse, friend, etc) may contact the CSC to let us know. The CSC agents enter that data into the SMDB on a screen where they mark the person as deceased. The second is the sites send us EMR data indicating a person is deceased via API. It is possible only one of these sources will be on record, and it is also possible for us to have BOTH the EMR data AND contact to the CSC.

We are having an issue on SMDB for Participation Status (variable SMMet_PartStatus_v1r0) for participants reported as deceased by EMR only:

- When the EMR data for a deceased record is sent, our system updates HdWd_Deceased_v1r0 to ‘yes’' but this is not automatically setting Participation Status to ‘deceased’.
- We noticed this by checking the connect_id of a participant who was reported by EMR only as deceased. Under Participation Status on the SMDB it should say “Deceased”, but instead it says “No Refusal” 
 
FYI - This automatic derivation for Participation Status seems to be working for the other two deceased participants we have on record (one was reported by CSC only and one was reported by both EMR and CSC). For both participants, it correctly say “Deceased” under Participation Status.

Tagging everyone here since it won't let me assign: @Davinkjohnson @sonyekere @brotzmanmj @robertsamm

**Comment by JoeArmani** [comment] 2024-01-09 16:43
Hi @kmazzilli,

I looked into this since I handled the EMR death data update. It sounds like 912301837 (participation status) needs to be assigned the value 618686157 (deceased) when EMR death data is sent through the API.

Is this correct? If yes, this is straightforward to implement, and I can confirm this has not yet been implemented (unknown/undocumented requirement).

Tagging the related EMR death data documentation and update for reference: https://github.com/episphere/connect/issues/823

**Comment by kmazzilli** [comment] 2024-01-10 20:30
@JoeArmani That looks correct to me! Thanks for looking into this.

**Comment by JoeArmani** [comment] 2024-01-10 22:07
@kmazzilli Okay, thanks. I'll have a PR for this shortly, which will be in the upcoming prod push.

@brotzmanmj
Re: existing participants where 912301837 (participation status) was not updated to 618686157 (deceased) alongside EMR deceased data API updates --

We can update the missed participants with a function we run alongside the prod push or handle it manually. I can have that function reviewed and ready by the upcoming push if you'd like. It looks like there are quite a few to update if we handle it manually instead.

Function process if needed:
(1) Search only participants where 857217152 (EMR participant deceased) = 303358909 (yes).
(2) update those participants: 912301837 (participation status) = 618686157 (deceased).

**Comment by JoeArmani** [comment] 2024-01-11 21:13
![Image](https://github.com/episphere/connect/assets/93854858/5d3b306f-b3db-4a9c-a42b-83c8f5f69c16)

![Image](https://github.com/episphere/connect/assets/93854858/8bf124b0-b9bf-49c8-a193-4e4bf90a767b)

PR Ready for review

**Comment by JoeArmani** [comment] 2024-01-12 16:07
Update 1/12/24:
The API update is merged to dev and ready for testing.
The cloud function to update participant status on missed participants is under development.

**Comment by brotzmanmj** [comment] 2024-01-12 16:23
@kmazzilli and @mnataraj92 can you work together to test this? thanks

**Comment by mnataraj92** [comment] 2024-01-12 16:33
I spoke with Sandra and Amelia. We were thinking about asking HP to push the EMR participant deceased variable (857217152) = yes in dev since they helped us with the initial EMR data testing. Once that is sent, Joe/Kelsey can check the back end to make sure that the participation status (912301837) = deceased and participant deceased (987563196) = yes. I will send out the communication to HP shortly.

**Comment by brotzmanmj** [comment] 2024-01-12 16:34
That sounds like a good plan, thank you Madhuri. And Kaitlyn can check the SMDB to make sure it shows up correctly there too.

**Comment by JoeArmani** [comment] 2024-01-12 21:21
This is in dev and being tested.
Approvals:
Firestore
SMDB (in app)

Awaiting: BQ

**Comment by mnataraj92** [comment] 2024-01-29 19:03
Notified Vijay this is ready for stage

**Comment by JoeArmani** [comment] 2024-01-30 15:33
Tested in stage: Firestore, BQ, and SMDB. Ready for prod.

**Comment by JoeArmani** [comment] 2024-02-01 13:44
Closing. This is in production.

**Closed by JoeArmani** 2024-02-01 13:44 UTC
