### ISSUE TITLE
Address unexpected behavior of client side thank you email for mouthwash kit completion + mw survey completion

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connect#939] opened 2024-03-25 19:02 UTC
In dev testing after merge on 3/15, client side email sent when mw home collection kit status = received AND mw survey = submitted has subject line, "Thanks for your mouthwash sample and survey!" is being delivered in some cases when appropriate (Connect ID 4876650727, delivered 3/21) but not delivered as expected to dev test participants (e.g., Connect ID 5708401166, undelivered as of 3/25). Stage sync will continue as planned, but we need to look further into the reason why the thank you email was not delivered to the expected participant during this round of dev testing. @we-ai

**Comment by we-ai** [comment] 2024-03-26 21:59
Based on what I know,  in our current code, the thank you email ("Thanks for your mouthwash sample and survey!") cannot be triggered by actions of submitting MW surveys in MyConnect site. It can only be triggered by confirming receipt of kit in biospecimen site. So there were no emails sent out after test accounts (connect IDs 4586732886 and 8432900634) submitting MW surveys.

I'm not sure whether the thank you email sending was designed this way. Please comment @brotzmanmj @mnataraj92 @depietrodeanna

**Comment by brotzmanmj** [comment] 2024-03-27 13:14
@we-ai  That is the correct behavior for the email "Thanks for your mouthwash sample and survey!"

There is another client side email along the lines of 'Thanks for your mouthwash samples, please submit your survey" which should get triggered upon receipt of the mouthwash kit if the survey is not already completed. It think this is the one that is only sometimes working? Or are we testing this wrong?

**Comment by we-ai** [comment] 2024-03-27 13:47
@brotzmanmj  If survey is not submitted, when kit receipt is confirmed, the thank you email is "We have your kit! Next, please complete your mouthwash sample survey".
This email was sent to connect ID 5708401166 (on 3-25) and 8432900634 (on 3-21).

**Comment by brotzmanmj** [comment] 2024-03-27 13:51
It seems all is working then. Thank you.

**Comment by brotzmanmj** [comment] 2024-03-27 13:54
@mnataraj92  can you confirm is those Connect IDs were as expected for that email, and was that in dev? Do we still need to test this scenario in stage today?

**Comment by mnataraj92** [comment] 2024-03-27 13:55
@brotzmanmj yes those were as expected for that email in dev. We need to test a KPHI scenario in stage but other than that we should be set.

**Comment by we-ai** [comment] 2024-03-27 14:00
I don't see any updates in this release impact client-side emails.
If the MW kit client-side email was tested and confirmed before, we may not need re-test it now since nothing changed in it. @brotzmanmj @mnataraj92

**Comment by we-ai** [comment] 2024-03-27 14:03
> Is the concept ID that we changed not part of the client side emails?

No, based on my checks. 
Please also check on this @Gbarra9

**Comment by Gbarra9** [comment] 2024-03-27 14:31
@brotzmanmj Confirming that the concept ID was not part of client side emails.

**Comment by mnataraj92** [comment] 2024-03-27 18:36
we're seeing everything as expected, @brotzmanmj can we close this?

**Comment by brotzmanmj** [comment] 2024-03-27 18:43
yes, thanks!

**Closed** 2024-03-27 18:44 UTC
