### ISSUE TITLE
SMDB Participation Status Error for Data Destruction (April Release) 

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#937] opened 2024-03-25 18:54 UTC
During data destruction testing, we noticed a couple issues with the SMDB:

(1) The participation status 'data destroyed' is showing as 'error' in the bubble field but looks correct in the header on the participant details page. 

(2) The participant summary page of SMDB is showing the wrong status for all of the survey and biospecimen collection completion statuses. It is still showing the old method of 'data destroyed' with a red X instead of the actual 'completed' status instead of retained 'completed/collected'

**Comment by brotzmanmj** [comment] 2024-03-26 20:32
Adding requirement here: There are fields on SMDB that show as 'data deleted' even when there is no data deleted, just the absence of data. Need to identify those and fix them in April. Noticed this specifically in the page headers.

**Comment by jhflorey** [comment] 2024-04-12 16:27
@brotzmanmj @mnataraj92 My changes already in dev. You can try in SMDB with Connect_ID = 6451999189

**Comment by brotzmanmj** [comment] 2024-04-12 17:44
@mnataraj92  and @robertsamm  can you check this? thanks

**Comment by robertsamm** [comment] 2024-04-12 18:46
Hi all, initial check looked good but CID 6451999189 did not have UP submitted or any study activities completed so will need to test in dev on a new participant with more activities completed to ensure all looks correct for this. Will create a new test pt with all study activities completed and report back.

**Comment by robertsamm** [comment] 2024-04-15 18:34
Hello @jhflorey, can you please run the data destruction process on these 3 individuals in DEV? They all have a status of data destruction requested=yes and data destruction form signed=yes.

Connect IDs:
7956451897
7916920108
4151371961

**Comment by jhflorey** [comment] 2024-04-16 13:29
@robertsamm it's done.

**Comment by robertsamm** [comment] 2024-04-16 18:54
Hi all, I found a couple of issues on the SMDB on the participant summary page after the data was destroyed for my test pts.

(1) SSN - the SSN survey flag is showing as 'none' when I had submitted SSN for this pt and we are retaining the SSN survey completion flag. I think I have identified the issue here.

- the survey status seems to be pointing to an older flag that isn't being retained in the stub record that has responses of 'none', '4 digits', 'all digits'). @mnataraj92 I can't find the CID/flag for this var in the DD, is it still being used?

- The SSN row on the SMDB should be changed so that the 'status' points to the new SSN status flag (126331570	SSN Survey	SrvSS_SSNSurvey_v1r0) that has the responses 'not started', 'started', 'submitted'. This is for all records, regardless of withdrawal/data destruction or SSN survey completion status.

![image](https://github.com/episphere/connect/assets/67074735/a87119e4-8e7d-4d70-82c4-2f66fedaf6eb)

(2) Biospecimen collection status is showing as 'not collected' for individuals who had biospecimens collected. This should be retained as part of the stub record.

- For research collections: blood, urine, and mouthwash are showing as 'not collected' when they were. See test pt Connect ID: 7956451897. 
- For clinical collections: blood and urine were showing as 'not collected' when they were, but the home mouthwash was showing as 'collected' correctly. See test pt Connect ID: 7916920108.
- I also checked the BSD and the flags are also showing as 'not collected' but there is a CXA number and date/timestamp associated with it.
- @mnataraj92 can you please check the data to see if we are retaining the flags for biospecimen blood, urine, and mouthwash collected for both research and clinical?

Research:
![image](https://github.com/episphere/connect/assets/67074735/82f24c4d-d301-4d4f-877a-7eda366ca874)
![image](https://github.com/episphere/connect/assets/67074735/8822fd3c-3e11-456d-bcbd-21c0b6b1d6ca)
Clinical:
![image](https://github.com/episphere/connect/assets/67074735/513aee55-ce00-4092-a538-01c86c41f067)

**Dev Test Accounts Below w/ activity statuses I pushed:**
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/ROBERT~1/AppData/Local/Temp/2/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/ROBERT~1/AppData/Local/Temp/2/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/ROBERT~1/AppData/Local/Temp/2/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>



Login Email | Connect ID | Name | Site | Research Biospec Col | Clinical Biospec Col | BOH | MRE | SAS | LAW | SSN Survey | B/U/M Survey | B/U Survey | Home M Survey | Men C Survey | COVID Survey | DD Req | DD Form Signed
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DDTest1@mailinator.com | 7956451897 | DDOne Middle Test | NCI | B/U/M Collected | No | Subm | Subm | Subm | Subm | All | Subm | N | N | Subm | Subm | 4/15 | 4/15
DDTest2@mailinator.com | 7916920108 | DDTwo Middle Test | NCI | No | B/U Collected   Home M Collected | Subm | Start | Start | Start | 4 digits | N | Subm | Subm | Start | Start | 4/15 | 4/15
DDTest3@mailinator.com | 4151371961 | DDThree Middle Test | NCI | No | No | N | N | N | N | N | N | N | N | N | N | 4/15 | 4/15




</body>

</html>

**Comment by mnataraj92** [comment] 2024-04-17 15:49
> Hi all, I found a couple of issues on the SMDB on the participant summary page after the data was destroyed for my test pts.
> 
> (1) SSN - the SSN survey flag is showing as 'none' when I had submitted SSN for this pt and we are retaining the SSN survey completion flag. I think I have identified the issue here.
> 
> * the survey status seems to be pointing to an older flag that isn't being retained in the stub record that has responses of 'none', '4 digits', 'all digits'). @mnataraj92 I can't find the CID/flag for this var in the DD, is it still being used?
> * The SSN row on the SMDB should be changed so that the 'status' points to the new SSN status flag (126331570	SSN Survey	SrvSS_SSNSurvey_v1r0) that has the responses 'not started', 'started', 'submitted'. This is for all records, regardless of withdrawal/data destruction or SSN survey completion status.
> 
> ![image](https://private-user-images.githubusercontent.com/67074735/322961962-a87119e4-8e7d-4d70-82c4-2f66fedaf6eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjQ2NTQsIm5iZiI6MTcxMzM2NDM1NCwicGF0aCI6Ii82NzA3NDczNS8zMjI5NjE5NjItYTg3MTE5ZTQtOGU3ZC00ZDcwLTgyYzQtMmY2NmZlZGFmNmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE0MzIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODkxNjFkZWIzOGQxMWExMzQ2OTQ0ZDM5MmUxMTc4MTFlN2Y3N2IyYzRlMzE4ZjE3NWY1ZjU3YmUxZDY1MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.69ihi_XrDoaJvKt41J-IVDpQrYk7UajlQFl0ROZ9B3c)
> 
> (2) Biospecimen collection status is showing as 'not collected' for individuals who had biospecimens collected. This should be retained as part of the stub record.
> 
> * For research collections: blood, urine, and mouthwash are showing as 'not collected' when they were. See test pt Connect ID: 7956451897.
> * For clinical collections: blood and urine were showing as 'not collected' when they were, but the home mouthwash was showing as 'collected' correctly. See test pt Connect ID: 7916920108.
> * I also checked the BSD and the flags are also showing as 'not collected' but there is a CXA number and date/timestamp associated with it.
> * @mnataraj92 can you please check the data to see if we are retaining the flags for biospecimen blood, urine, and mouthwash collected for both research and clinical?
> 
> Research: ![image](https://private-user-images.githubusercontent.com/67074735/322963413-82f24c4d-d301-4d4f-877a-7eda366ca874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjQ2NTQsIm5iZiI6MTcxMzM2NDM1NCwicGF0aCI6Ii82NzA3NDczNS8zMjI5NjM0MTMtODJmMjRjNGQtZDMwMS00ZDRmLTg3N2EtN2VkYTM2NmNhODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE0MzIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNDJjYjcxYzBmMTMwYjQ3ZTFkOGQ5Njg4N2Y0NDExM2FmZTUwYzc3ODk3MmI2ZDcyM2U1YjJkNTYyNmZjODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wk7J8Raqzgf7U49yYAjKesyK_iBEYH1z2HQYjwMqs4o) ![image](https://private-user-images.githubusercontent.com/67074735/322963496-8822fd3c-3e11-456d-bcbd-21c0b6b1d6ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjQ2NTQsIm5iZiI6MTcxMzM2NDM1NCwicGF0aCI6Ii82NzA3NDczNS8zMjI5NjM0OTYtODgyMmZkM2MtM2UxMS00NTZkLWJjYmQtMjFjMGI2YjFkNmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE0MzIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMzBmMWIxMjEyNjY2MzRiOWFlNWYzMTIzNDMzYzBjMjNjMzE4Y2MyNTIwMTA4ODQzMzg4NzRmZDM2MmQ2NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rBR7zQArwfuvWpyw6hpcUGipRFwZKQ4CX_uGiFDBJoA) Clinical: ![image](https://private-user-images.githubusercontent.com/67074735/322963686-513aee55-ce00-4092-a538-01c86c41f067.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjQ2NTQsIm5iZiI6MTcxMzM2NDM1NCwicGF0aCI6Ii82NzA3NDczNS8zMjI5NjM2ODYtNTEzYWVlNTUtY2UwMC00MDkyLWE1MzgtMDFjODZjNDFmMDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE0MzIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MzI3OTVlMTlkOWM2MzY0MjZhMWU5MTJiN2UxMGVmMzBjZjFkMjQ4MTZlMTM2YjA5NTFkMzBjMTk3NTYwMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lk9pyZ4CliuUZZdf10OAJqKB5HfCS0tfIRcKp7QL6Zg)
> 
> **Dev Test Accounts Below w/ activity statuses I pushed:**
> 
> Login Email	Connect ID	Name	Site	Research Biospec Col	Clinical Biospec Col	BOH	MRE	SAS	LAW	SSN Survey	B/U/M Survey	B/U Survey	Home M Survey	Men C Survey	COVID Survey	DD Req	DD Form Signed
> [DDTest1@mailinator.com](mailto:DDTest1@mailinator.com)	7956451897	DDOne Middle Test	NCI	B/U/M Collected	No	Subm	Subm	Subm	Subm	All	Subm	N	N	Subm	Subm	4/15	4/15
> [DDTest2@mailinator.com](mailto:DDTest2@mailinator.com)	7916920108	DDTwo Middle Test	NCI	No	B/U Collected Home M Collected	Subm	Start	Start	Start	4 digits	N	Subm	Subm	Start	Start	4/15	4/15
> [DDTest3@mailinator.com](mailto:DDTest3@mailinator.com)	4151371961	DDThree Middle Test	NCI	No	No	N	N	N	N	N	N	N	N	N	N	4/15	4/15

Nope the old flag isn't in the dictionary anymore, I think this was before we were marking variables as deprecated so it is just removed. As Amelia mentioned, the survey flag is CID 126331570 with options 
972455046	0=Not Started
615768760	1=Started
231311385	2=Submitted

For Connect ID 7956451897, BQ is showing that baseline blood collected is no. Baseline urine and baseline MW collected is also no. 

For Connect ID 7916920108, Clinical blood collected and clinical urine collected are both null. MW kit is showing as received in BQ so it's consistent with what you're seeing in the dashboard.

**Comment by mnataraj92** [comment] 2024-04-17 15:50
Nope the old flag isn't in the dictionary anymore, I think this was before we were marking variables as deprecated so it is just removed. As Amelia mentioned, the survey flag is CID 126331570 with options
972455046 0=Not Started
615768760 1=Started
231311385 2=Submitted

For Connect ID 7956451897, BQ is showing that baseline blood collected is no. Baseline urine and baseline MW collected is also no.

For Connect ID 7916920108, Clinical blood collected and clinical urine collected are both null. MW kit is showing as received in BQ so it's consistent with what you're seeing in the dashboard.

**Comment by robertsamm** [comment] 2024-04-17 16:05
Thanks @mnataraj92, for Connect ID 7956451897 we did collect baseline research blood, urine, and mouthwash and for Connect ID 7916920108 we did collect clinical blood and urine before requesting data destruction. See screenshot below from SMDB BEFORE data destruction was completed. This seems to indicate that the blood, urine, and mouthwash collection flags being retained in the stub record? @jhflorey and @jeannewu can you please look into this?

![image](https://github.com/episphere/connect/assets/67074735/d688be06-b7d9-4c1a-a2d7-e1a14fd626c2)
![image](https://github.com/episphere/connect/assets/67074735/dfe44d04-a9ee-4aca-8bcd-a9b490dba26a)

**Comment by jeannewu** [comment] 2024-04-17 17:39
Hi, Amelia, the pictures are too murky here. Here attached is a copy of the stub variables for these three participants from the participants_JP table with my notations on the biospecimen part (color: red for blood, blue for mouthwash and green for urine). please check them and let me know if anything is needed. 
[Dev_participants_tables_3ConnectIDs_stubvariables_notes_04172024.xlsx](https://github.com/episphere/connect/files/15015171/Dev_participants_tables_3ConnectIDs_stubvariables_notes_04172024.xlsx)

**Comment by robertsamm** [comment] 2024-04-17 21:02
Hi all, updates below. A couple of the issues found still need to be addressed in this github issue. The other issues that were discovered during this testing will be moved to a separate github issue. 

For this github issue:
**(1) The SSN survey status on the SMDB is not pointing to the correct flag.** This should be pointing to CID 126331570 SSN Survey SrvSS_SSNSurvey_v1r0 with options below. This should fix the issue where the survey flag is showing as not being retained on the SMDB when it actually is. @jhflorey can you update this on the SMDB?
972455046 0=Not Started
615768760 1=Started
231311385 2=Submitted

**(2) Participation status 'data destroyed' is showing as 'error' in the bubble field**: this looks fixed in dev. Looks good.

**(3) Issue where the participant summary page of SMDB is showing the wrong status for all of the survey and biospecimen collection completion statuses (Showing the old method of 'data destroyed' instead of the retained 'completed/collected status'**: This looks fixed in dev for all fields in pt summary pg (except for SSN and biospecimen samples collected which are caused by separate issues).

To be moved to separate github issues:
**(4) Biospecimen blood, urine, mouthwash collection flags showing as 'not collected'**: Madhuri and Jing discovered the reason for this. Only the biospecimen vars in the participants table that are nested under CID 173836415 are being retained in the stub record. The flags for baseline biospec collected are not nested under that CID so are not being retained. @mnataraj92 is working to get a full list of the variables that are biospecimen related and not nested under 173836415 so that we can identify which need to be added to the stub record. This includes:
1 d_167958071 Base Ur Collected    BioFin_BaseUrineCol_v1r0
2 d_684635302 Base MW Collected    BioFin_BaseMouthCol_v1r0
3 d_878865966 Base Blood Collected BioFin_BaseBloodCol_v1r0

**(5) Restore biospecimen collection data in PROD for individuals who had samples collected and data destroyed.** We will need to restore the biospecimen collection vars for participants in prod who had biospec collected and had data destroyed and are now showing as no specimens collected. Madhuri and I are meeting tomorrow to identify the list of participants for this.

**Comment by jhflorey** [comment] 2024-04-18 15:48
@robertsamm @mnataraj92 i've already updated SSN survey. Please recheck in dev.

**Comment by robertsamm** [comment] 2024-04-18 16:09
Thanks @jhflorey , SSN survey status looks good in dev SMDB. This is ready for stage.

**Comment by robertsamm** [comment] 2024-04-22 18:57
@jhflorey Can you please run the data destruction process in STAGE on these 3 test Connect IDs? All 3 have requested data destruction and signed the destruction form.
5488539602
7721121201
1268641103

**Comment by jhflorey** [comment] 2024-04-23 13:00
@robertsamm @jeannewu Please check it.

**Comment by robertsamm** [comment] 2024-04-23 13:19
@jhflorey tested in stage. On the SMDB, the participation status bubble field looks correct and the status flags on the participant summary page are showing the correct status. All looks good. This is ready for prod.

**Comment by jeannewu** [comment] 2024-04-23 13:30
@jhflorey 
just checked and compared with their data on the stub variables before data destruction. Everything looks consistent on both before and after (especially the biospecimen collections, refusal and withdrawal reasons). Thanks a lot.

**Closed** 2024-04-25 13:16 UTC
Labels: CCC Priority 1
