### ISSUE TITLE
Add filtering to API filter option

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#817] opened 2023-11-13 20:38 UTC
Add logic to filter participants from payload that would otherwise be returned by getParticipants API (specifically the "filter") option. This returned payload should only have participants that are verified and have not withdrawn from the study.

**Comment by JoeArmani** [comment] 2024-01-02 17:05
Next in, gathering requirements...

**Comment by anthonypetersen** [comment] 2024-01-05 19:28
1) I think the goal for this long term is that we can easily add new filters as needed, but no additional ones are needed at the moment. There's the NORC Birthday Card effort coming up, but that doesn't need to be worried about right now.
2) I'm leaning towards leaving things as is. If we need to filter off those participants in our dashboards, we can do so there when needed. Sites can do the same as they see fit.
3) I think that's a good idea since they aren't PII fields. Maybe we start with just Connect_ID in the beginning and see the feedback we get?
4) Nothing at the top of my mind, great questions!

**Comment by JoeArmani** [comment] 2024-01-09 22:20
Notes for getFilteredParticipants API users

• The `type` parameter is deprecated.

• One or more of the following query params must be included in the request:
`firstName`, `lastName`, `email`, `phone`, `dob`, `connectId`, `token`, `studyId`, `checkedIn`

•All data in the participant profile is returned by default. If you only want to return certain data, use the `selectedFields` param in your query. selectedFields is an array of Concept IDs. Connect_ID is always included. Ex:
`.../getFilteredParticipants?firstName=jane&selectedFields=399159511,996038075`
will return first name, last name, and Connect ID for all participants with the first name Jane.

**Comment by JoeArmani** [comment] 2024-01-10 22:51
final local testing, will issue PR shortly.

**Comment by jhflorey** [comment] 2024-01-12 16:34
Approved and left a minor comment.

**Comment by JoeArmani** [comment] 2024-01-12 20:54
Got approvals from Tony & Vaishnavi as well - thank you.

**Comment by JoeArmani** [comment] 2024-01-12 20:58
Items to test:
-This new getFilteredParticipants API. Documentation here: https://github.com/episphere/connect/issues/817#issuecomment-1883893946
-Quick check on Biospecimen Participant search (minor updates to the filterDB function that drives the search).
-Quick check on SMDB Participant search (minor updates to the filterDB function that drives the search).

This is in dev and ready for testing.

**Comment by brotzmanmj** [comment] 2024-01-16 14:12
Hi @sonyekere we are happy to test. Can you tell us what we should be expecting to see that has changed? Or is this just to confirm that nothing has changed?

**Comment by sonyekere** [comment] 2024-01-16 14:24
Hi @brotzmanmj. Joe shared that this will just be a quick sanity check since the new API required minor updates. He's tested this locally, if an Ops member could do just a quick participant search test in Biospecimen and SMDB.

**Comment by kmazzilli** [comment] 2024-01-18 21:31
I checked the participant search features on both SMDB and the biospecimen dashboard using various search features and different types of participants and everything looked ok on my end.

**Comment by brotzmanmj** [comment] 2024-01-19 17:33
@sonyekere and @mnataraj92 can you coordinate the testing of the new API in dev with 1-2 sites?

**Comment by JoeArmani** [comment] 2024-01-19 20:38
#### Detailed documentation: https://app.box.com/s/b1agjc8abpw3ca1xlns95s8wdp4mflzj

**Comment by JoeArmani** [comment] 2024-01-25 20:06
@anthonypetersen
Do you have input on this question we received during site dev testing:

The site dev asked about the 'limit' and 'page' options from the getParticipants API.

These don't currently extend into our existing 'filter' functionality in the getParticipants API (or the new getFilteredParticipants API). They aren't built into the filterDB function for targeted participant search. They could be if needed. Do you see a use for `limit` or `page` in our filtering API in the future?
The only use case I can think of is a first-name-only search for a very common first name, but I am passing along the question. Thanks.

**Comment by anthonypetersen** [comment] 2024-01-25 20:13
@JoeArmani I feel like this might not be an immediate need until we add something with fewer options to differentiate participants

**Comment by JoeArmani** [comment] 2024-01-25 20:18
Perfect and agreed - thanks

**Comment by JoeArmani** [comment] 2024-01-25 20:53
tested in dev, ready for stage

**Comment by mnataraj92** [comment] 2024-01-29 19:02
Notified Rob from MF this is ready for stage

**Comment by mnataraj92** [comment] 2024-01-29 21:42
Rob confirmed this looks as expected in stage

**Comment by JoeArmani** [comment] 2024-02-01 13:43
Closing, this is in production.

**Closed by JoeArmani** 2024-02-01 13:43 UTC
Labels: API
