### ISSUE TITLE
BPTL receipt csv file update for Chicago Clinical Collections (Biospecimen)

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#998] opened 2024-05-02 18:24 UTC
BPTL's Receipt csv needs to be updated for Chicago's clinical collections.  
The Connect Tube Mapping file has been updated for the tubes Chicago will use in their clinical collections.
The file is located here: https://nih.app.box.com/file/1306346523951

**Comment by amber-emmes** [comment] 2024-05-03 18:00
This has been merged into dev and is ready for dev testing.

**Comment by erincschwartz** [comment] 2024-05-08 16:28
@amber-emmes Tested in Dev, not ready for Stage. 

Vial types should read 10 mL for each tube type

Volume should also read 10mL for each tube 

The file showing default values for is located here: https://nih.app.box.com/file/1306346523951

**Comment by amber-emmes** [comment] 2024-05-09 12:55
To be clear, the problem is that it currently reads as `10 ml` and not `10 mL`, case-sensitive, under the vial types? And you want the volume to be changed from reading `10` to reading `10 mL`? To be clear, these are the values currently listed for UCM Clinical:

```
{
          '0001': ['10 ml Serum separator tube', 'SST', 'Serum', '10'],
          '0002': ['10 ml Serum separator tube', 'SST', 'Serum', '10'],
          '0003': ['10 ml Vacutainer', 'Lithium Heparin', 'WHOLE BL', '10'],
          '0004': ['10 ml Vacutainer', 'EDTA = K2', 'WHOLE BL', '10'],
          '0060': ['Streck Tube', 'Streck DNA', 'WHOLE BL', '10'],
          '0006': ['10 ml Vacutainer', 'No Additive', 'Urine', '10']
        },
```

And here is the corresponding section of the provided document, which to my eye appears to match apart from some listing mL instead of ml:

![image](https://github.com/episphere/connect/assets/160774541/4c1487bb-8d5a-4e14-a300-7d801c847af1)

If this isn't what you meant, let's hop on a call to go over this. Thanks!

**Comment by amber-emmes** [comment] 2024-05-09 13:05
It appears that it isn't reading the provided values correctly. Likely, there's a key mismatch at work. Can you provide me the steps you are using to replicate this and I'll take a look? Thanks!

**Comment by wyattks** [comment] 2024-05-09 13:19
Chicago entered the collection informatoin yesterday and shipped the ollection.  Erinreceived the shipment in BPTL's Package receipt tab.  I went to BPTL's create csv file tab and set the date in the Enter a Date box to 5/8/2024 and clicked on create file.
Let me know if you have additional questions.

**Comment by amber-emmes** [comment] 2024-05-09 15:09
I've updated the key to what I believe is the correct value. Please try again.

**Comment by erincschwartz** [comment] 2024-05-21 17:49
Tested in Stage, ready for Prod

**Comment by amber-emmes** [comment] 2024-05-23 15:53
This is now in prod.

**Closed by amber-emmes** 2024-05-23 15:53 UTC
Labels: Biospecimen Dashboard, CCC Priority 1
