### ISSUE TITLE
Automate Deleting Uninvited Participants

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#636] opened 2023-04-28 13:44 UTC
* Create code job that finds all uninvited participants (using CID 288972510 for reference) and deletes Firestore document
* Need to determine action path if participant is verified and if they also have additional documents (biospecimen, ssn, modules, notifications, etc)

**Comment by mnataraj92** [comment] 2024-02-06 19:27
2/6/24: had a call with Sanford regarding the Uninvited Recruits variable (CID 288972510). 

This variable is intended to remove participants from our system, entirely. (i.e. NO data would exist for them if this flag is set to yes.) It should be so the cleanup job won't run on participants if they're marked "verified" but we'll need to re-test that before turning it and the data destruction on.

@brotzmanmj  mentioned that there should be additional restrictions placed on this. Once these are confirmed, @mnataraj92 will make a note in the Data Dictionary.

@Davinkjohnson  mentioned there was another use case (from UoC) that will need to be considered when placing restrictions on how/who can have their data removed.

**Comment by mnataraj92** [comment] 2024-02-06 19:28
Github issue to have this added to Operations Report: https://github.com/episphere/connect/issues/892

**Comment by mnataraj92** [comment] 2024-02-06 19:41
@brotzmanmj are there any restrictions on which participants this should be run on? And title specifications for the table?

**Comment by brotzmanmj** [comment] 2024-02-06 19:49
Suggested restriction: Should be only for records that have no activity associated with them, meaning no sign in using that token/pin. The sites using this are UChicago, Marshfield, Sanford so should check with each of them to see if this restriction will hamper their work. Also @mnataraj92 please check the existing data in BQ to see who we have this uninvited flag for so far (from which sites, and what are the sign in, consent, verification status of those individuals).

**Comment by mnataraj92** [comment] 2024-02-13 21:06
Hi @brotzmanmj we currently don't have anyone where the uninvited flag = yes

**Comment by brotzmanmj** [comment] 2024-02-13 21:08
interesting, ok thanks

**Comment by brotzmanmj** [comment] 2024-02-23 19:38
Update: I reached out to MF, SF and UC today to see if adding the restriction to records that have no sign in or any subsequent action by the participant associated with them will impact their use cases in any negative way. Waiting to hear back.

**Comment by mnataraj92** [comment] 2024-03-07 17:17
UC has no issues with the new restrictions. SF also has no issues with the new restrictions. They have one outstanding question regarding duplicates that I need to double check with Nicole on, and I will send a reply. We still have not heard back from MF regarding if they have any issues with the new restrictions; I will follow up with them today.

I spoke to Michelle regarding the test scenarios we'll send to UC, MF, and SF regarding the uninvited variable:
1. Test one scenario where they push the uninvited flag for someone that has not used their pin/token
2. Test one scenario where they push the uninvited flag for someone that has used the pin/token (ex: signed in) 
3. Test one scenario where the uninvited flag is pushed for a verified participant 
 
Scenario 1 is normal and doesn't test any of the new restrictions. We should receive the uninvited flag and our system should delete this record when the program is run

Scenario 2- we should not delete this record as their token/pin has been used. @anthonypetersen a couple of questions- I think Maddi had asked if they send an uninvited flag on an individual who has in fact used their token, if it's possible to kick back an API error to the site? In this scenario, would we still receive the uninvited flag = yes, but the code on our end would be set up to not delete this record?

Scenario 3- we should not delete this record as this person is verified. Similarly to scenario 2, would the site receive an error if they try to push the uninvited recruits variable to us? Or would we still receive the uninvited flag = yes, but our code would be set up to not delete this record?

A couple of additional questions regarding testing-
@jhflorey When the sites start testing, would you be able to run the program manually in dev and stage to remove the uninvited recruits? Have you also had a chance to program the new restrictions for this uninvited recruits variable yet? If not, could you please post an update when you do so? Thank you!!

**Comment by anthonypetersen** [comment] 2024-03-07 17:37
@mnataraj92 why would we still want to accept the Uninvited Flag in the API for Scenarios 2 and 3? This flag is intended to have a specific use case of being a marker that the document needs to be deleted.

**Comment by brotzmanmj** [comment] 2024-03-07 17:39
@anthonypetersen I didn't know it was an option not to accept the flag. Can we do just reject the call? And they would get an error message?

**Comment by anthonypetersen** [comment] 2024-03-07 17:42
@brotzmanmj Yes, we can reject the call and return an error message.

**Comment by brotzmanmj** [comment] 2024-03-07 17:43
@anthonypetersen great then let's do that

**Comment by mnataraj92** [comment] 2024-03-07 22:03
Perfect, thanks! Updated scenarios/outcomes here:

1. Test one scenario where they push the uninvited flag for someone that has not used their pin/token
2. Test one scenario where they push the uninvited flag for someone that has used the pin/token (ex: signed in)
3. Test one scenario where the uninvited flag is pushed for a verified participant

Scenario 1 is normal and doesn't test any of the new restrictions. We should receive the uninvited flag and our system should delete this record when the program is run

Scenario 2- we should not delete this record as their token/pin has been used. We will reject the call and return an error message.

Scenario 3- we should not delete this record as this person is verified. We will reject the call and return an error message.

**Comment by brotzmanmj** [comment] 2024-03-08 13:58
Hi @mnataraj92 please draft an explanation of the purpose and proper use of the uninvited flag. After I review, I'll ask you to circulate to all the sites (and cc: NORC) and give them each one week to respond with confirmation that they are clear as to the intended use. If they have any other use cases for it, they need to have them approved by the CCC before they proceed so we don't inadvertently delete records. Then we'll ask NORC will add to each of the site specific SOPs.

**Comment by jhflorey** [comment] 2024-03-11 14:16
Hi @mnataraj92 sorry for the late reply. We can run manually in dev to remove data. i do not have permission in stage. I have not implement new restrictions yet.

**Comment by jhflorey** [comment] 2024-03-11 14:58
@brotzmanmj @mnataraj92 could you describe more detail about the new restrictions?

**Comment by mnataraj92** [comment] 2024-03-11 15:11
@jhflorey the restrictions can be found earlier in this thread. We would like this variable to only be used for records that have no activity associated with them, meaning no sign in using that token/pin (or any other part of the workflow- if the recruit has consented, submitted UP, or has gone through the verification process, then the record should not be deleted. As Tony mentioned earlier, if the sites send the variable for someone that has used their token/pin, then we should reject the call and return an error message.

**Comment by mnataraj92** [comment] 2024-03-18 22:35
Emailed MF, SF, and UC to test the 3 scenarios above in dev

**Comment by mnataraj92** [comment] 2024-03-19 17:28
This did not work as expected for Marshfield and scenarios 2 and 3 did not return an error. I have forwarded Rob's email to @jhflorey and the operations team.

**Comment by jhflorey** [comment] 2024-03-21 13:39
@mnataraj92  i've ready merge the new changes in dev. Please help test it.

**Comment by mnataraj92** [comment] 2024-03-21 13:54
Thank you! I have let the sites know they can test this in dev.

**Comment by mnataraj92** [comment] 2024-03-25 14:13
UC and MF tested, ready for stage

**Comment by mnataraj92** [comment] 2024-03-26 16:02
Reached out to UC and MF to test in stage

**Comment by mnataraj92** [comment] 2024-03-27 18:14
tested in stage, Joe confirmed back end looks good. ready for prod.

**Comment by sonyekere** [comment] 2024-03-29 13:50
Closing issue, item is in Prod.

**Closed** 2024-03-29 13:52 UTC
