### ISSUE TITLE
Biospecimen/Shipping Performance Enhancements - Phase1

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#685] opened 2023-08-02 12:52 UTC
@JoeArmani @Gbarra9 please add details of the first increment here.

**Comment by JoeArmani** [comment] 2023-08-02 14:17
We're optimizing in-app data handling for the first shipping dashboard performance enhancement.
Related: https://github.com/episphere/biospecimen/issues/548

•Implement a custom data structure that aggregates the healthcare provider's boxes, associated bags, and associated specimen details into ‘detailedBoxes’.
•Implement a state management solution to standardize data access in the app.
•Handle box data, bag data, specimen data, and 'detailedBoxes' with the state management solution.
•After the initial load, minimize data fetching operations where possible (existing write operations are necessary and unchanged).
•Solve slow loading issue with Box Manifests using state management solution.

**Comment by JoeArmani** [comment] 2023-08-11 18:54
Update: Just posted a large ~1900 line PR handling in-app changes for the shipping interface. It is a major update and we expect this to take some time for the team to review.

Gene and I have left the 'reports' or 'BPTL' sections at this point, though we have made sure those sections are compatible and working with the newly implemented updates. Those sections can be handled similarly in the future if deemed important, and the speed improvement would be significant.

Our working document moving forward - this is a work in progress and will evolve as we go. It's a great outline for now:

√—1— Moving forward, we need to make sure that the shipped and received properties are added to the boxes collection.
•When a new box is created in the biospecimen shipping dashboard, the shipped and recieved properties should be added to the box and written to firestore on box creation.
•The initial value for both is always cId.no.
•When a box is shipped, the shipped property should be updated to cId.yes and written to firestore. This way, moving forward, we will always have the shipped property on every box in the boxes collection. We can query on that property to get unshipped boxes.


—2— Look into how box numbering is handled and figure out the best way to handle it moving forward.
(1) Do we want to keep the box numbering system we have now?
(2) Gene's idea: figure out numbering server-side. We currently determine highest box number with getAllBoxes() function.
(3) An additional option for handling box numbering:
-Generate current timestamp -> use Firestore .orderBy(recency of *create* date).limit(1).get(). Need to test this as it would be ideal (fast, low data in transit, single db read).
-This would pull the most recently created box. We could grab that box number and increment by 1 to get the next box number.


—3— Function to update all boxes in Firestore boxes collection.
•This function will run locally on one of our machines to update the boxes collection.
(1) Get all boxes from the boxes collection.
(2) Iterate through each box.
(3)      For each box, check whether shipped and received properties exists.
(4)      If shipped property exists, that document is already updated. No operation necessary.
(5)      If shipped property does not exist, add the shipped property, set it to cId.no, and update the document.
(6)      If received property exists, that document is already updated. No operation necessary.
(7)      If received property does not exist, add the received property, set it to cId.no, and update the document.


—4— Function to update all specimens in Firestore Biospecimen collection.
//TODO Make decision on whether shipped data resides at the bag level or the specimen level. One option is to place a shipped flag on the entire bag, then individually mark each specimen. The bag only gets marked shipped.completed when all specimens in the bag are marked.

 
—5— Search function for unshipped boxes.
•Create new else if clause for this in ConnectFaas -> biospecimen.js -> searchSpecimen() -> searchUnshippedShipments() (this is a new function we'll have to create).
•This will be similar to the searchShipment() function, but with one additional .where() clause.
	else if (searchType === 'unshipped') {
•This will be used in the search function for the shipping dashboard
•Using the additional .where() clause will allow us to pull fewer documents from the database. This has the following benefits:
      (1) Fewer documents to pull from the database means faster search times.
      (2) Fewer documents to pull from the database means less data to send to the client.
      (3) We will no longer have to filter out shipped documents server side or client side. We 
won't be pulling those documents in the first place.
	Pseudocode:
	searchUnshippedShipments() Biospecimen collection
	      const snapshot = await db.collection('biospecimen')
	          .where(healthCareProvider == siteCode) //this already exists in the search
	          .where(shipped == no) //this is the new clause
	          .get()
•Then, since we're not pulling shipped boxes anymore, we can get rid of the submitShipment filtering that happens later in the searchShipments function.
•IMPORTANT: The method for filtering availableCollections (the ‘Available Collections’ list) currently uses all boxes and all finalized specimens to calculate available specimens. This will need a major refactor (and will be significantly more efficient after refactoring. 

(6) Once everything is in place, we need to handle the way specimen data is fetched from the 'biospecimen' Firestore collection. This is currently a significant bottleneck.
 
Order of operations - fewest updates, data consistency.
(1) update boxes collection to include shipped property on all boxes.
(2) Optimize box numbering so the system works when we're pulling unshipped boxes only. getAllBoxes() cannot 
	be used for this moving forward. It is too inefficient.
(3) Update boxes collection to include shipped and received property on all boxes.
	(A) in app on box creation
	(B) cloud function to update existing boxes
(4) Update biospecimen collection to include shipped property on either:
	-individual specimens???
	-the entire bag???
	-array of shipped/unshipped specimens???
	-This needs to get updated:
		-in the app when specimen is finalized
		-cloud function to update existing specimens
(5) Implement searchUnshippedShipments() or searchUnshippedBoxes() function in ConnectFaas -> biospecimen.js -> searchSpecimen() -> searchUnshippedShipments() so we can pull unshipped boxes.
(6) Update fetching of the biospecimen collection for available collections.

**Comment by StephanieWeinstein** [comment] 2023-08-14 17:01
Hi Joe,
Thanks for all of the above!  tomorrow in our meeting can we discuss: 

> 
> —4— Function to update all specimens in Firestore Biospecimen collection.
> //TODO Make decision on whether shipped data resides at the bag level or the specimen level. One option is to place a shipped flag on the entire bag, then individually mark each specimen. The bag only gets marked shipped.completed when all specimens in the bag are marked.

we want to make sure stray tubes are considered. Also maybe you can explain the new box numbering ideas.  thank you!

**Comment by JoeArmani** [comment] 2023-08-14 17:11
Hi @StephanieWeinstein, perfect. I think we're on the same page with the importance of stray tubes and I look forward to that discussion. I'd also like to discuss concurrency - situations where multiple people in the same location are working in the shipping dashboard.

**Comment by JoeArmani** [comment] 2023-08-18 19:18
Update: Added current details on Boxes and next steps here: https://github.com/episphere/connect/issues/650#issuecomment-1684330426

**Comment by JoeArmani** [comment] 2023-08-29 15:34
Update on today's ConnectFaas PR:

Found Issue: Sometimes the ‘remove bag’ button causes multiple bags to be removed.

This behavior is a result of an incorrect box rearranging algorithm in the API. It was first brought up by a lab worker at HP 2 months ago and was reconfirmed in testing.

A PR was submitted this morning to properly handle bag removal.

Important keys:
	-650224161 “Bag/Container/Thing 1”
	-136341211 “Bag/Container/Thing 2”
	-503046679 “Bag/Container/Thing 3”
	-313341808 “Bag/Container/Thing 4”
	-668816010 “Bag/Container/Thing 5”

Steps to reproduce (with soon-to-be-updated existing function):
-removeBag removes multiple bags in the list (sometimes)
	-when you remove the first bag in the list, it only removes one bag.
	-when you remove any other bag, multiple bags are removed.

		-remove 'thing 2' (not expected behavior)
			'thing 1' is gone
			'thing 2' exists
			'thing 3' is gone

		-add a bag
			'thing 1' exists
			'thing 2' exists

		-add a bag
			'thing 1' exists
			'thing 2' exists
			'thing 3' exists

		-remove 'thing 1' (expected behavior)
			updated 'thing 1' exists
                    updated 'thing 2' exists

		-add a bag
			'thing 1' exists
			'thing 2' exists
			'thing 3' exists

		-remove 'thing 3' (not expected behavior)
			'thing 1' is gone
			'thing 2' exists
			'thing 3' is gone
			
About the new version of `removeBag` in today's PR: This function updates bag removal handling and adds error handling.
(1) Remove specified bag(s).
(2) Create new sortedBox.
(3) Iterate old box, placing foundKeys in order in the new sortedBox (Thing 1, Thing 2, Thing 3, etc...).
(4) Copy remaining keys to sortedBox.
(5) Update firestore.
(6) Return Success/Failure (Error) based on outcome of the update.

**Comment by JoeArmani** [comment] 2023-09-05 17:39
Log data from dev testing:

Box 73 (Firestore):
√ Bags match
√ Specimens match
√ Shipper name (expected)
√ Orphans flag (no, expected)
√ Login site is correct (13)
√ Site specific location is correct (111111111)
√ Shipment Courier is Fedex
√ Tracking number match
√ Package condition: package in good condition
√ Shipped flag = yes
√ Shipment received flag = yes
√ Comments are empty (expected)

Biospecimen Collection CXA114477 (Firestore):
√ All shipped tubes have received timestamp
√ No comments are included

Biospecimen Collection CXA336699 (Firestore):
√ All shipped tubes have received timestamp
√ No comments are included

—
Box 81 (Firestore):
√ Bags match
√ Specimens match
√ Shipper name (expected)
√ Orphans flag (no, expected)
√ Login site is correct (13)
√ Site specific location is correct (111111111)
√ Shipment Courier is Fedex
√ Tracking number match
√ Package condition: package in good condition
√ Shipped flag = yes
√ Shipment received flag = yes
√ Comments are empty (expected)

Biospecimen Collection CXA225588 (Firestore):
√ All shipped tubes have received timestamp
√ No comments are included

—
Box 83 (Firestore):
√ Bags match
√ Specimens match
√ Shipper name (expected)
√ Orphans flag (no, expected)
√ Login site is correct (13)
√ Site specific location is correct (111111111)
√ Shipment Courier is Fedex
√ Tracking number match
√ Package condition: Cold Packs - none
√ Shipped flag = yes
√ Shipment received flag = yes
√ Comments are empty (expected)

Biospecimen Collection CXA888881 (Firestore):
√ All tubes have received timestamp
√ No comments are included

Biospecimen Collection CXA999991 (Firestore):
√ All tubes have received timestamp
√ No comments are included

—
Box 71 (Firestore):
√ Bags match
√ Specimens match
√ Shipper name (expected)
√ Orphans flag (no, expected)
√ Login site is correct (13)
√ Site specific location is correct (222222222)
√ Shipment Courier is Fedex
√ Tracking number 111111111000
√ Package condition: Cold Packs - warm
√ Shipped flag = yes
√ Shipment received flag = yes
√ Comments are empty (expected)

Biospecimen Collection CXA111898 (Firestore):
√ All shipped tubes have received timestamp
√ No comments are included

Biospecimen Collection CXA557844 (Firestore):
√ All shipped tubes have received timestamp
√ No comments are included
NOTE: Tubes 0003 and 0006 have do not ship deviations and are not on manifest (expected).

—
Box 75 (Firestore):
√ Bags match
√ Specimens match
√ Shipper name (expected)
√ Orphans flag (no, expected)
√ Login site is correct (13)
√ Site specific location is correct (222222222)
√ Shipment Courier is Fedex
√ Tracking number 444444444777
√ Package condition: package in good condition
√ Shipped flag = yes
√ Shipment received flag = yes
√ Comments are empty (expected)

Biospecimen Collection CXA776102 (Firestore):
√ All tubes have received timestamp
√ No comments are included

Biospecimen Collection CXA448710 (Firestore):
√ All tubes have received timestamp
√ No comments are included

—
Box 82 (Firestore):
√ Bags match
√ Specimens match
√ Shipper name (expected)
√ Orphans flag (no, expected)
√ Login site is correct (13)
√ Site specific location is correct (222222222)
√ Shipment Courier is Fedex
√ Tracking number 666644447777
√ Package condition: package in good condition
√ Shipped flag = yes
√ Shipment received flag = yes
√ Comments are empty (expected)

Biospecimen Collection CXA189774 (Firestore):
√ All tubes have received timestamp
√ No comments are included

Biospecimen Collection CXA550077 (Firestore):
√ All tubes have received timestamp
√ No comments are included

**Comment by JoeArmani** [comment] 2023-09-05 17:41
Log data from stage testing:

Box 10 (Firestore):
√ Bags match
√ Specimens match
√ Shipper name (expected)
√ Orphans flag (no, expected)
√ Login site is correct (548392715) - Henry Ford Health System
√ Site specific location is correct (752948709) Henry Ford Main Campus
√ Shipment Courier is Fedex
√ Tracking number 000000000007
√ Package condition: N/A
√ Shipped flag = yes
√ Shipment received flag = no
√ Comments are empty (expected)

Biospecimen Collection CXA000564 (Firestore):
√ No shipped tubes have received timestamp
√ Additional Notes: “NCI stage testing”

Biospecimen Collection CXA000872 (Firestore):
√ No shipped tubes have received timestamp
√ Additional Notes: “NCI stage testing. No discard deviation”

Box 11 (Firestore):
√ Bags match
√ Specimens match
√ Shipper name (expected)
√ Orphans flag (no, expected)
√ Login site is correct (548392715) - Henry Ford Health System
√ Site specific location is correct (752948709) Henry Ford Main Campus
√ Shipment Courier is Fedex
√ Tracking number 000000000008
√ Package condition: N/A
√ Shipped flag = yes
√ Shipment received flag = no
√ Comments are null (expected)

Biospecimen Collection CXA000871:
√ No shipped tubes have received timestamp
√ Additional Notes: “Stage testing NCI-adding in discard deviation”
√ Tube 0001 has leak deviation

Biospecimen Collection CXA000872 (Firestore):
√ No shipped tubes have received timestamp
√ Additional Notes: “NCI stage testing. No discard deviation”

**Comment by wyattks** [comment] 2023-09-05 17:43
THis is ready for Prod

**Comment by JoeArmani** [comment] 2023-09-13 19:41
Closing - future updates in Phase 2 (link directly above this post).

**Closed by JoeArmani** 2023-09-13 19:41 UTC
