### ISSUE TITLE
Extra Collection ID Sequence Numbers (0050-0054) Not Showing in Manifest - (Biospecimen)

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#576] opened 2022-09-13 16:08 UTC
The clinical box manifests do not display any extra Collection ID labels (0050-0054) when used in place of the tube sequence numbers (0001, 0002, etc.) and default to the tube sequence numbers. (See screenshot below) Kathleen confirms that Firestore does have the 0050-0054 sequence numbers, but they are showing incorrectly in the manifest.

![Screen Shot 2022-09-13 at 11 58 01 AM](https://user-images.githubusercontent.com/85250133/189950727-46a0b0ce-7207-4919-a2eb-edf06eedaec7.png)

**Comment by HopkinsDC** [comment] 2022-09-13 19:13
@Gbarra9 The extra-label sequence numbers (0050-0054) are correct on the Collection Data Entry review page, but not in shipping. (see screenshots below)

![Data Entry Page](https://user-images.githubusercontent.com/85250133/189989690-7479fc48-bbef-4228-beab-614fc0a8605c.png)
![Review Page](https://user-images.githubusercontent.com/85250133/189989691-5ae96992-f2c1-4776-aa73-a24806300095.png)
![Shipping](https://user-images.githubusercontent.com/85250133/189989694-85b3f4ec-b0b2-4169-adc5-46132ccc47f0.png)

**Comment by HopkinsDC** [comment] 2022-09-22 16:24
@Gbarra9 The extra-label sequence numbers (0050-0054) are **correct** when I generate a CVS file in the BPTL dashboard

**Comment by anthonypetersen** [comment] 2023-01-31 18:21
* Clinical Box Manifest is the only place this isn't showing at the moment
* @HopkinsDC to confirm if this is the case for Research Box Manifest

**Comment by wyattks** [comment] 2023-08-29 20:43
Norma has requested the csv list the tube sequence numbers as what they are supposed to be and not the 0050-0054.  

Reason is when tubes come in with 50-54 sequence, they have to do a lot of work to track down what tube it was supposed to be to aid when they processs the samples. This is supposed to translate to the correct tube type on our csv file. 
Norma says since it does not happen too often, where the 0050 and 0054 sequence numbers are used, it does not need to be super high priority, but it would help them to have this fixed.

**Comment by bransteitterbr** [comment] 2023-12-07 17:06
I just wanted to confirm that this is the expected behavior for the packing the shipping screen.
![image](https://github.com/episphere/connect/assets/135354377/cd69a8cf-85f7-4501-b7a4-dce1071946af)

**Comment by bransteitterbr** [comment] 2023-12-08 14:58
@wyattks Thanks for the clarification.  Can you also provide me with a set of steps to generate the csv that needs modified as well.

**Comment by wyattks** [comment] 2023-12-08 19:28
Hi @bransteitterbr  I have attached of what is needed.  Hopefully this makes sense.  I tried to give a comprehensive explanation. 
Let me know if this doesn't make any sense!

[0050 to 0054 labels.pptx](https://github.com/episphere/connect/files/13620155/0050.to.0054.labels.pptx)

**Comment by sonyekere** [comment] 2023-12-12 18:38
Work to continue in Jan, Brian is making progress.

**Comment by sonyekere** [comment] 2024-01-02 18:12
PR ready for team review - 1/2

**Comment by Gbarra9** [comment] 2024-01-03 18:22
PR Review Status - Approved, added some comments

**Comment by JoeArmani** [comment] 2024-01-05 17:16
PR reviewed and approved

**Comment by jhflorey** [comment] 2024-01-10 15:55
Approved PR https://github.com/episphere/biospecimen/pull/647

**Comment by sonyekere** [comment] 2024-01-17 21:56
Merged to Dev. Ready for testing

**Comment by wyattks** [comment] 2024-01-22 21:39
IDs showing up in files and on dashboard as expected.  Ready for Stage.

**Comment by wyattks** [comment] 2024-01-31 17:49
Tested in Stage
Ready for production

**Comment by sonyekere** [comment] 2024-02-06 14:10
In Prod for the January release.

**Closed by sonyekere** 2024-02-06 14:10 UTC
Labels: Bug, Biospecimen Dashboard, Clinical, Priority 1
