### ISSUE TITLE
Restrict Accession ID Page to Numeric Values Only

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#652] opened 2023-06-15 12:30 UTC
On the Accession ID linking page in the clinical biospecimen dashboard, make the scanning fields for both the blood and urine Accession ID only accept numeric values; The fields should **not** accept string data.

**Comment by Davinkjohnson** [comment] 2023-07-25 17:08
Unable to reproduce in Dev/Stage, only reported once in prod. Closing until this is seen again.

**Closed by Davinkjohnson** 2023-07-25 17:08 UTC
Labels: enhancement, Biospecimen Dashboard, Clinical, Priority 1, Backend
