### ISSUE TITLE
Account creation- Prevent duplicate accounts

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#43] opened 2019-10-15 20:24 UTC
Ensure that participants who create an account do not create a different account with a different email address or a different method (e.g. phone or Google) when they sign in again.

**Comment by danielruss** [comment] 2020-01-19 04:44
Deduplication of accounts should they occur

**Comment by danielruss** [comment] 2020-04-07 16:37
duplicate of #2

**Comment by hzhao392** [comment] 2020-09-21 14:40
Handled by sites in verification SOP

**Comment by hzhao392** [comment] 2020-09-21 14:40
We will need to test this from the sites

**Comment by anthonypetersen** [comment] 2023-07-28 14:54
being referenced in other issues

**Closed by anthonypetersen** 2023-07-28 14:54 UTC
