### ISSUE TITLE
Sync 'sendgridTracking' to BQ and data cleanups (April Release)

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#835] opened 2023-12-04 15:39 UTC
Currently SendGrid data are saved to `sendgridTracking` collection in Firestore. These data need to be in BigQuery for analysis. Below tasks need to be done:
- Sync `sendgridTracking` collction to BigQuery in November release
- Merge `sendgridTracking` collection to `notifications` collection in December release. This is specified in issue [#828](https://github.com/episphere/connect/issues/828).
- After above tasks are finished, remove `sendgridTracking` in Firestore and BigQuery. Also remove code syncing `sendgridTracking` data.

**Comment by jhflorey** [comment] 2024-04-03 13:55
Hi @jacobmpeters @we-ai , i've already clean up data in dev. Could you help check it and confirm. After that i will remove sendgridTracking collection.

**Comment by we-ai** [comment] 2024-04-03 14:06
@jhflorey Please check the data first.

**Comment by jhflorey** [comment] 2024-04-03 14:18
i've already checked

- Merged 5420 docs from sendgridTracking into notifications
- Updated 840 notifications docs  that have snake_cake fields to camelCase

@jacobmpeters please help double check

**Comment by jacobmpeters** [comment] 2024-04-03 15:36
The `notifications` BQ table in DEV was last updated Apr 3, 2024, 11:27:14 AM UTC-4.

The schema still contains the snake_case fields.

| fullname | mode | type |
|:---:|:---:|:---:|
| notification | NULLABLE | RECORD |
| uid | NULLABLE | STRING |
| read | NULLABLE | BOOLEAN |
| notificationSpecificationsID | NULLABLE | STRING |
| id | NULLABLE | STRING |
| notificationType | NULLABLE | STRING |
| category | NULLABLE | STRING |
| attempt | NULLABLE | STRING |
| email | NULLABLE | STRING |
| token | NULLABLE | STRING |
| deliveredDate | NULLABLE | STRING |
| processedDate | NULLABLE | STRING |
| processedStatus | NULLABLE | BOOLEAN |
| deliveredStatus | NULLABLE | BOOLEAN |
| notificationId | NULLABLE | STRING |
| openStatus | NULLABLE | BOOLEAN |
| openDate | NULLABLE | STRING |
| bounceStatus | NULLABLE | BOOLEAN |
| bounceDate | NULLABLE | STRING |
| bounceReason | NULLABLE | STRING |
| droppedDate | NULLABLE | STRING |
| droppedReason | NULLABLE | STRING |
| droppedStatus | NULLABLE | BOOLEAN |
| phone | NULLABLE | STRING |
| messageSid | NULLABLE | STRING |
| errorMessage | NULLABLE | STRING |
| errorCode | NULLABLE | STRING |
| status | NULLABLE | STRING |
| dropped_date | NULLABLE | STRING |
| dropped_status | NULLABLE | BOOLEAN |
| dropped_timestamp | NULLABLE | INTEGER |
| dropped_reason | NULLABLE | STRING |
| deferredDate | NULLABLE | STRING |
| deferredStatus | NULLABLE | BOOLEAN |
| error_message | NULLABLE | STRING |
| error_code | NULLABLE | STRING |
| queued_date | NULLABLE | STRING |
| sent_date | NULLABLE | STRING |
| delivered_date | NULLABLE | STRING |
| open_date | NULLABLE | STRING |
| open_timestamp | NULLABLE | INTEGER |
| open_status | NULLABLE | BOOLEAN |
| failedDate | NULLABLE | STRING |
| connect_id | NULLABLE | STRING |
| notification_id | NULLABLE | STRING |
| isLocal | NULLABLE | BOOLEAN |
| unsubscribeStatus | NULLABLE | BOOLEAN |
| unsubscribeDate | NULLABLE | STRING |
| accepted_date | NULLABLE | STRING |
| undeliveredDate | NULLABLE | STRING |
| notification.time | NULLABLE | STRING |
| notification.title | NULLABLE | STRING |
| notification.body | NULLABLE | STRING |

**Comment by jhflorey** [comment] 2024-04-03 17:25
@jacobmpeters already updated the script and run again. Please help check again

Note: We will not update `connect_id` since it is not related with sendgrid feature.

**Comment by jacobmpeters** [comment] 2024-04-03 20:27
@jhflorey The schema looks appropriate to me now. I do not any redundant snake_case fields.

Last updated Apr 3, 2024, 4:22:06 PM UTC-4...

| fullname | mode | type |
|:---:|:---:|:---:|
| uid | NULLABLE | STRING |
| read | NULLABLE | BOOLEAN |
| notificationSpecificationsID | NULLABLE | STRING |
| id | NULLABLE | STRING |
| notificationType | NULLABLE | STRING |
| category | NULLABLE | STRING |
| attempt | NULLABLE | STRING |
| email | NULLABLE | STRING |
| token | NULLABLE | STRING |
| deliveredDate | NULLABLE | STRING |
| processedDate | NULLABLE | STRING |
| processedStatus | NULLABLE | BOOLEAN |
| deliveredStatus | NULLABLE | BOOLEAN |
| openStatus | NULLABLE | BOOLEAN |
| openDate | NULLABLE | STRING |
| notificationId | NULLABLE | STRING |
| bounceStatus | NULLABLE | BOOLEAN |
| bounceDate | NULLABLE | STRING |
| bounceReason | NULLABLE | STRING |
| errorMessage | NULLABLE | STRING |
| errorCode | NULLABLE | STRING |
| phone | NULLABLE | STRING |
| messageSid | NULLABLE | STRING |
| status | NULLABLE | STRING |
| failedDate | NULLABLE | STRING |
| sentDate | NULLABLE | STRING |
| queuedDate | NULLABLE | STRING |
| droppedDate | NULLABLE | STRING |
| droppedReason | NULLABLE | STRING |
| droppedStatus | NULLABLE | BOOLEAN |
| deferredDate | NULLABLE | STRING |
| deferredStatus | NULLABLE | BOOLEAN |
| unsubscribeStatus | NULLABLE | BOOLEAN |
| unsubscribeDate | NULLABLE | STRING |
| acceptedDate | NULLABLE | STRING |
| undeliveredDate | NULLABLE | STRING |
| notification.time | NULLABLE | STRING |
| notification.title | NULLABLE | STRING |
| notification.body | NULLABLE | STRING |

**Comment by jhflorey** [comment] 2024-04-08 13:36
@jacobmpeters Could you please check the snake_case fields in stage and prod. my guess is there is no snake_case field in product and lots of fields in stage.

**Comment by jacobmpeters** [comment] 2024-04-08 17:58
@jhflorey There are no snake_case fields in the `notifications` table in prod, but the following snake_case fields are present in stg: `delivered_status`, `delivered_timestamp`, `delivered_date`, `processed_timestamp`, `processed_date`, `processed_status`, `open_status`, `open_date`, `open_timestamp`

**Comment by jacobmpeters** [comment] 2024-04-08 18:31
@jhflorey You requested via email that I query the participation status of all of the participants whose records are in the `sendgridTracking` table in BQ in prod but are not in the `notifications` table. I did that with the following query:

```sql
-- Find unique notification_id's from the sendgridTracking table that are not present in the notifications table
-- and join with the participants table to get the d_912301837 (aka, participation status) field
SELECT DISTINCT s.notification_id, s.token, p.d_912301837
FROM `nih-nci-dceg-connect-prod-6d04.Connect.sendgridTracking`   s
LEFT JOIN `nih-nci-dceg-connect-prod-6d04.Connect.notifications` n ON s.notification_id = n.id
LEFT JOIN `nih-nci-dceg-connect-prod-6d04.Connect.participants`  p ON s.token = p.token
WHERE n.id IS NULL AND s.notification_id IS NOT NULL;
-- 6221 total results as of Apr 8, 2024 at 2 PM
```
I've shared the results via Box since this is production data: https://nih.app.box.com/file/1495678650092

I hope this is helpful for your checks.

**Comment by jhflorey** [comment] 2024-04-09 13:45
@jacobmpeters there seems to be 61 notifications belongs to participant whose data has been destroyed

**Comment by brotzmanmj** [comment] 2024-04-09 19:30
That is correct, that's what we want to ensure

**Comment by jhflorey** [comment] 2024-04-10 14:31
@we-ai Do you think there are any cases where the data is not saved in the notification but is sent to the email.

**Comment by jhflorey** [comment] 2024-04-11 13:05
@jacobmpeters thanks for your confirm about the snake_case in stage.
Are you sayin that the records that you listed are in the sendgridTracking table but are not in the notifications table` => yup, i'm still investigating the root cause of this issue.

**Comment by jhflorey** [comment] 2024-04-16 14:49
@jacobmpeters i've already merged data from sendgridTracking into notifications `68788/75070`. there are 6282 cases in `sendgridTracking` but do not exist in notifications.

We can check it with query `isMerged = 104430631`

**Comment by we-ai** [comment] 2024-04-17 21:44
I checked those docs in `sendgridTracking` that don't have a match in `notifications`. Majority of those docs were created on 12-20-2023, when +20k newsletters were sent out. No errors can be found in saving email records when sending out the newsletters on Dec 20 or in other occasions. The cause of un-matched docs problem is unclear to me. Good news is that this problem didn't happen after February release.
I'll do more data checking/analysis and will share when I have new findings.

**Comment by jhflorey** [comment] 2024-04-18 13:29
@we-ai thanks for your support and information.

**Closed** 2024-04-25 13:16 UTC
Labels: CCC Priority 1
