### ISSUE TITLE
RCA Variables to be Added (July Release)

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connect#866] opened 2024-01-25 18:12 UTC
Additional variables under consideration for a future release.  Pending decision from leads and RCA working group:

- vital status
- cancer stage: waiting to gain a better understanding of the development of the “suspense file” and how to capture the evolution of stage and likely other characteristics of the cancer
- confirmation by the sites that the participant has been informed of their diagnosis through manual chart review (yes/no flag; [SOP](https://nih.app.box.com/folder/167573740836) indicates that this is part of the RCA process for the sites)

historical information here: https://github.com/episphere/connect/issues/675

**Comment by cunnaneaq** [comment] 2024-02-08 20:04
RCA discussion on 2/7 resulted in the following decisions:
- Add variable for site confirmation that the participant has been informed of their diagnosis through manual chart review
- Update of primary anatomical site – This variable should not overwrite the previous site information and all previous site information should be retained. 

@FrogGirl1123 @mnataraj92 @JoeArmani 

Using this as documentation of the decision.  I will follow-up again with the decision on vital status, and when variable names and question text have been added to the DD change log.

**Comment by brotzmanmj** [comment] 2024-02-08 20:08
@cunnaneaq Can you explain what's meant by update of primary anatomical site? If they sent 'primary site' for an occurrence and we have those data in our system, then they get new information that the site information for that occurrence is different than originally thought, they should be able to send a new primary site for that occurrence but not overwrite the old one? And will one supersede the other in terms of what we consider to be the truth?

**Comment by cunnaneaq** [comment] 2024-02-08 22:12
@brotzmanmj Apologizes, I posted that pre-maturely.  Discussions within the RCA WG are still ongoing.  Please see my updated comment with that point removed.

**Comment by brotzmanmj** [comment] 2024-02-08 22:23
OK thanks!

**Comment by mnataraj92** [comment] 2024-03-14 19:18
https://github.com/episphere/connect/issues/921 need to discuss data structure for date variable to indicate that RCA data was received because we'd like this variable to be in the participants table as it will be retained in the stub record, and there can be more than one cancer occurrence per person.

**Comment by cunnaneaq** [comment] 2024-03-19 20:50
New variables requiring manual chart review have been discussed with the sites, documentation [here](https://nih.app.box.com/file/1475963538575).  Variables have also been added to the data dictionary and have had concept IDs assigned.  Mia approves moving forward with this in the April release

**Comment by mnataraj92** [comment] 2024-03-20 15:56
@brotzmanmj I think we need Nicole's @FrogGirl1123 input on where the variable should be stored and what the nesting would look like to account for more than once cancer occurrence per person https://github.com/episphere/connect/issues/921

**Comment by brotzmanmj** [comment] 2024-03-20 16:15
OK thanks @mnataraj92 when that information is available, please doucment it here

**Comment by Davinkjohnson** [comment] 2024-04-16 21:01
@cunnaneaq Can you please ensure all the most recent requirements are in this issue and close #921 ?

**Comment by cunnaneaq** [comment] 2024-04-19 22:15
Recent updates:

- CCC will not collect and store date of RCA data transmission in the participants table - issue #921 closed.
- question text and responses updated and added to the data dictionary change log on 4/19.  I will update when approved
- Removing cancer stage from DD under RCA
- If the participant is confirmed alive by manual chart review, the API should only allow a response of "yes" to the question, "Has the cancer diagnosis and the participant's awareness of their diagnosis been confirmed by manual review of the participant's chart?"
- If the participant is confirmed deceased by manual chart review, the API will accept all responses responses - “yes” “no” and “unknown” to “Has the cancer diagnosis and the participant's awareness of their diagnosis been confirmed by manual review of the participant's chart?”
- RCA variables cannot be updated or overwritten

Pending Decisions:
- API functionality if the participant's vital status is "unknown" at the time of manual chart review - email to confirm sent 4/19
- Double entry of pathology accession number - waiting to hear if the sites will manually enter this or if it is data pulled from EPIC.

**Comment by cunnaneaq** [comment] 2024-05-01 18:31
RCA SOP: https://nih.app.box.com/file/1065926614330
The SOP reflects the recent changes to the RCA variables and conditions

**Comment by JoeArmani** [comment] 2024-05-06 15:35
@cunnaneaq I’ve had a chance to go through the RCA Variables SOP. Here's my understanding. Please update/correct/elaborate on anything that looks incorrect or unclear. Thanks!

**Concept IDs (new since previous implementation):**
844209241 — Question: participant awareness of cancer
•values: yes, no, unknown (concept IDs)
•required: Yes

114227122 — Question: is alive at chart review
•values: yes, no, unknown (concept IDs)
•required: yes

421730068 — pathology accession number
•value: text string
•required: no

**Rules:**
if 114227122 = yes, 844209241 must be yes. Else, block request.
if 114227122 = no, 844209241 can be yes, no, or unknown.
if 114227122 = unknown, 844209241 can be yes, no, or unknown.

**Questions:**
421730068 - Is there a specific format to this text such as length or pattern of letters/numbers, or is that determined by the site? The DD currently specifies 'Char' and length = max 800.

**Comment by cunnaneaq** [comment] 2024-05-06 18:55
@JoeArmani this all looks correct!

- The concept IDs for alive, dead, and unknown responses to 114227122 are now in the DD
- The variables listed above are the new concept IDs since the last implementation, but reminder that there are updates to the question text for other variables (345545422, 149205077, and 868006655)

**Comment by JoeArmani** [comment] 2024-05-06 21:50
@cunnaneaq Perfect. Thanks. I checked 345545422, 149205077, and 868006655, confirming that the response structure in the code is unchanged.

New Concept IDs:
'Alive': 337516613
'Dead': 646675764

This is in development.

**Comment by JoeArmani** [comment] 2024-05-09 23:47
The data structure documentation (also linked in the SOP) has been updated.
• https://nih.app.box.com/file/1393159438842
• https://nih.app.box.com/file/1404701245622

**Comment by JoeArmani** [comment] 2024-05-10 13:27
PR ready for review: https://github.com/episphere/connectFaas/pull/595

**Comment by JoeArmani** [comment] 2024-05-10 14:18
@cunnaneaq This is in dev and ready for testing.

**Comment by JoeArmani** [comment] 2024-05-20 13:46
Reverted for May dev -> stage push. The site isn't available to test yet, so we're keeping the untested changes out of stage and prod.

**Comment by JoeArmani** [comment] 2024-06-27 13:27
This is back in dev and ready for testing

**Comment by JoeArmani** [comment] 2024-08-13 13:44
This is back in dev and ready for testing

**Comment by Davinkjohnson** [comment] 2024-08-23 18:57
Melanie and @cunnaneaq confirmed today that the KP testing in Dev looked good for this. Ready for stage.

**Comment by cunnaneaq** [comment] 2024-08-28 20:15
@JoeArmani and @mnataraj92 confirmed data looked good in Firestore and BQ - ready for prod

**Comment by JoeArmani** [comment] 2024-08-29 15:00
Closing, this is in prod.

**Closed by JoeArmani** 2024-08-29 15:00 UTC
Labels: CCC Priority 1
